feature: implemented gem info
artipie/gem-adapter pull request #100
Opened 2021-07-15 09:32 UTC by g4s8

- Implemented Gem metadata parser SDK supprted different format
 - Implemented Gem info API slice
 - Refactored existing code to use shared Ruby runtime
 - Other refactoring includes: 1) split interfaces and implementations of
   Ruby metadata parser; 2) moved slices to http package;
   3) using copy storage from artipie/http instead of custom copy-paste
   4) removed json matcher copy-paste from other modules
   5) removed unused classes

Fixes: #85
Closes: #96

*Note: sorry for big PR, it includes all required changes in SDK for release deadline 16.07.2021*

2021-07-15 13:05 UTC, olenagerasimova requested changes
@g4s8 just one comment. Also, as I know nothing about gem, maybe Alexey should also review this PR?

2021-07-15 13:39 UTC, g4s8 commented on src/main/java/com/artipie/gem/UncheckedSupplier.java
> +public final class UncheckedSupplier<T> implements Supplier<T> {
@olenagerasimova actually it can't, since `Scalar` doesn't implement `Supplier<T>` from `java.util.function` which is required for many functional interfaces in standard libs, so it's needed to change it like this:
```diff
+ CompletableFuture.supplyAsync(() -> new UncheckedScalar(() -> someAction()).value())
- CompletableFuture.supplyAsync(new UncheckedSupplier(() -> someAction()))
```

2021-07-15 14:33 UTC, olenagerasimova commented on src/main/java/com/artipie/gem/UncheckedSupplier.java
> +public final class UncheckedSupplier<T> implements Supplier<T> {
@g4s8 and what is wrong with `() -> new UncheckedScalar(() -> someAction()).value()`? The right repository for the `UncheckedSupplier` is `asto`, otherwise it will be implemented in each adapter.

2021-07-16 05:51 UTC, g4s8 commented on src/main/java/com/artipie/gem/UncheckedSupplier.java
> +public final class UncheckedSupplier<T> implements Supplier<T> {
@olenagerasimova because of redundant complexity: `func(lambda(object(lambda).call())` is harder to read comparing to `func(object(lambda))`. And I don't see reasons to wrap some call with an object which doesn't provide required interface directly and also needed to be wrapped.

2021-07-16 05:59 UTC, g4s8 commented
@olenagerasimova thanks, added `@todo` for moving `UncheckedSupplier` https://github.com/artipie/gem-adapter/pull/100/commits/4dd7c8b9e8a151cdbea8fd063066ef4fc75c9886

2021-07-16 06:32 UTC, olenagerasimova approved these changes
@g4s8 ok, thanks

2021-07-16 06:33 UTC, merged