Issue #104 Rename gem to its name and version
artipie/gem-adapter pull request #105
Opened 2021-07-21 12:38 UTC by milkysoft

When a new gem is being pushed with `gem push`, save it not with random name, but use gem name and version

2021-07-22 07:46 UTC, g4s8 requested changes
@milkysoft please check my comments

2021-07-22 07:46 UTC, g4s8 commented on src/main/java/com/artipie/gem/ruby/RubyGemIndex.java
> +                    .concat("File.rename('%s', dir + spec.name + '-'")
What is the point of renaming files in ruby instead of Java?

2021-07-22 07:46 UTC, g4s8 commented on src/main/java/com/artipie/gem/Gem.java
> +                        index.update(tmp);
This rename doesn't have effect because it doesn't rename file in the storage, only in local temporary directory

2021-07-26 06:32 UTC, kirill-h5i commented
@g4s8 ping

2021-07-26 06:44 UTC, g4s8 requested changes
@milkysoft please check my review

2021-07-26 06:44 UTC, g4s8 commented on src/main/java/com/artipie/gem/ruby/RubyGemIndex.java
> +    public void rename(final Path path) {
@milkysoft I dont think that `rename` is a good method for `Index` class: why index can rename? It's just a metadata parser implementation. So let's keep only related code in this index implementation, e.g. the method to extract spec name from gem

2021-07-26 06:44 UTC, g4s8 commented on src/main/java/com/artipie/gem/ruby/RubyGemIndex.java
> +                "ind='%s'.rindex('/')\n"
What is `ind`? These ruby lines are too cryptic and hard to understand.

2021-07-26 06:44 UTC, g4s8 commented on src/main/java/com/artipie/gem/ruby/RubyGemIndex.java
> +                    .concat("File.rename('%s', dir + spec.name + '-'")
Remember that this code can be read and maintained by random people from open source who knows java, not ruby. Also, as described above, the rename operation is not logically good for index parser

2021-07-26 06:44 UTC, g4s8 commented on src/main/java/com/artipie/gem/Gem.java
> +                        index.update(tmp);
This comment is not valid, since we copy all blobs from tmp storage.

2021-07-30 09:56 UTC, closed without merging