WIP: Add dependencies route
artipie/gem-adapter pull request #106
Opened 2021-07-25 06:38 UTC by milkysoft

close #97

2021-08-04 07:58 UTC, g4s8 commented
@milkysoft also, please pay attention to PR style: https://github.com/artipie/artipie/blob/master/CONTRIBUTING.md

2021-09-10 09:22 UTC, g4s8 requested changes
@milkysoft please check some initial comments

2021-09-10 09:22 UTC, g4s8 commented on src/main/java/com/artipie/gem/Gem.java
> +     * Get info Ruby gem.
Why do we need to load Ruby gem into memory?

2021-09-10 09:22 UTC, g4s8 commented on src/main/java/com/artipie/gem/Gem.java
> +    public CompletionStage<byte[]> getRubyFile(final Key filename) {
Key is not a file

2021-09-10 09:22 UTC, g4s8 commented on src/main/java/com/artipie/gem/Gem.java
> +                    final Key thekey = feature.get(10, TimeUnit.MILLISECONDS);
Please don't use blocking calls, vertx server may stop the request processor on such behavior

2021-09-10 09:22 UTC, g4s8 commented on src/main/java/com/artipie/gem/Gem.java
> +                    filecontent = Files.readAllBytes(file.toPath());
Why do you convert path to file and then back to path? You can just use `Files.readAllBytes(path)`

2021-09-10 09:22 UTC, g4s8 commented on src/main/java/com/artipie/gem/Gem.java
> +                } catch (final IOException | TimeoutException | InterruptedException
`InterruptedException` should not be handled in a such way. Please read the documentation about correct `InterruptedException` handling

2021-09-10 09:22 UTC, g4s8 commented on src/main/java/com/artipie/gem/Gem.java
> +     * Get info Ruby gem.
Two same methods?

2021-09-10 09:22 UTC, g4s8 commented on src/main/java/com/artipie/gem/Gem.java
> +                return new Copy(this.storage, key -> key.string().contains(filename.string()))
`contains` is not correct here because gem name could be in the repository name, e.g. user `rails` may keep package `gviz` in his repository, then the key will be `rails/gviz`

2021-09-10 09:22 UTC, g4s8 commented on src/main/java/com/artipie/gem/Gem.java
> +                return new Copy(this.storage, key -> key.string().contains(gems.get(0).string()))
Why we copy only first gem here? And same problem for `contains`

2021-09-10 09:22 UTC, g4s8 commented on src/main/java/com/artipie/gem/Gem.java
> +    private CompletionStage<Key> getGemFile(final Key gem, final boolean exact,
The javadoc and method name are confusing here: `getGemFile` returns `Key`, not file. "Find gem in a given path." accepts `Key` not path.

2021-09-10 09:22 UTC, g4s8 commented on src/main/java/com/artipie/gem/Gem.java
> +     * @param fallout Is fallout
What is fallout? Method behavior should be clear from Javadoc description

2021-09-10 09:22 UTC, g4s8 commented on src/main/java/com/artipie/gem/Gem.java
> +                        key -> key.string().contains(gem.string()) && key.string().endsWith(gemstr)
Same here: we can match `rails/gviz.gem` where gem is `rails`

2021-09-10 09:22 UTC, g4s8 commented on src/main/java/com/artipie/gem/Gem.java
> +                    return result;
This code has too many duplications and perform the same work multiple times - no need to build a stream just to count and then build another stream for filter. 
Also, it's not clear why do you use `List result` which is always containing only one element.

2021-09-10 09:22 UTC, g4s8 commented on src/main/java/com/artipie/gem/http/ApiGetSlice.java
> +        final String deproute = "/api/v1/dependencies";
No need to put all HTTP handlers into one `Slice`, you can introduce more slices to handle new endpoints. One slice per endpoint

2021-09-10 09:22 UTC, g4s8 commented on src/main/java/com/artipie/gem/http/ApiGetSlice.java
> +     * Process dependency route.
Please use meaningful method names and javadocs. Try to imagine that you see this code for the first time, how would you understand what does this method do?

2021-09-10 09:22 UTC, g4s8 commented on src/main/java/com/artipie/gem/http/ApiGetSlice.java
> +                .toCompletableFuture().get();
Don't ever use blocking calls. It's only acceptable in unit tests or some corner cases like futures joining

2021-09-10 09:22 UTC, g4s8 commented on src/main/java/com/artipie/gem/http/ApiGetSlice.java
> +        } catch (final InterruptedException | ExecutionException exc) {
`InterruptedException` should not be handled in a such way, please check documentation. You can find a very good summary from documentation here: https://stackoverflow.com/a/3976377/1723695

2021-09-10 09:22 UTC, g4s8 commented on src/main/java/com/artipie/gem/http/GemSlice.java
> +                ),
Same problem here: no need to handle all endpoints in one slice

2021-09-10 09:22 UTC, g4s8 commented on src/main/java/com/artipie/gem/ruby/IDependencies.java
> +public interface IDependencies {
1) why do we need this interface? 2) what does this `I` prefix mean?

2021-09-10 09:22 UTC, g4s8 commented on src/main/ruby/dependencies.rb
> +    include com.artipie.gem.ruby.IDependencies
No need to implement some interfaces here, we don't expose it outside the package. You can just call class method directly as we did previously

2021-09-10 09:22 UTC, g4s8 commented on src/main/ruby/dependencies.rb
> +            puts(gem)
Please remove stdout logging from production code, you can use only `Logger` from slf4j

2021-09-13 04:58 UTC, milkysoft commented on src/main/ruby/dependencies.rb
> +            puts(gem)
@g4s8 , agreed, fixed in latest commit

2021-09-13 04:58 UTC, milkysoft commented on src/main/java/com/artipie/gem/Gem.java
> +                    filecontent = Files.readAllBytes(file.toPath());
@g4s8 , agreed, fixed in latest commit

2021-09-13 04:58 UTC, milkysoft commented on src/main/java/com/artipie/gem/Gem.java
> +                    final Key thekey = feature.get(10, TimeUnit.MILLISECONDS);
@g4s8 , agreed, fixed in latest commit

2021-09-13 05:16 UTC, milkysoft commented on src/main/java/com/artipie/gem/http/GemSlice.java
> +                ),
@g4s8 , agreed, fixed in latest commit

2021-09-14 06:33 UTC, milkysoft commented on src/main/java/com/artipie/gem/Gem.java
> +     * Get info Ruby gem.
@g4s8 , we use the same functionality for all responses, althoough we can reconsider our approach

2021-09-14 06:33 UTC, milkysoft commented on src/main/java/com/artipie/gem/Gem.java
> +    public CompletionStage<byte[]> getRubyFile(final Key filename) {
@g4s8 , I confirm **Key** here is arbitrary name

2021-09-14 06:34 UTC, milkysoft commented on src/main/ruby/dependencies.rb
> +    include com.artipie.gem.ruby.IDependencies
@g4s8 , unfortunately all efforts to convert RubyObject to RubyString failed until now

2021-09-16 04:59 UTC, milkysoft commented on src/main/ruby/dependencies.rb
> +    include com.artipie.gem.ruby.IDependencies
@g4s8 , fixed in latest commit

2021-09-16 05:00 UTC, milkysoft commented on src/main/java/com/artipie/gem/ruby/IDependencies.java
> +public interface IDependencies {
@g4s8 , fixed in latest commit

2021-09-16 08:19 UTC, g4s8 commented on src/main/java/com/artipie/gem/Gem.java
> +    public CompletionStage<byte[]> getRubyFile(final Key filename) {
@milkysoft but `key` is just a locator of some data in key-value storage, it could be a file or could not

2021-09-23 14:35 UTC, closed without merging