Issue #103 Enhance output JSON
artipie/gem-adapter pull request #107
Opened 2021-07-28 11:25 UTC by milkysoft

2021-08-02 07:56 UTC, g4s8 requested changes
@milkysoft please check my comments

2021-08-02 07:56 UTC, g4s8 commented on src/main/java/com/artipie/gem/GemMeta.java
> +    JsonObject info(Path gem);
@milkysoft it's wrong change: we may have multiple format outputs: json and yaml. This interface is an abstraction for both types and it could be used to fetch some spec metadata from gem. Json object is too concrete type

2021-08-02 07:56 UTC, g4s8 commented on src/main/java/com/artipie/gem/Gem.java
> +    public CompletionStage<javax.json.JsonObject> info(final String gem) {
And same here: the return type is generic `<T>` here, since we may have different output types for same spec

2021-08-02 07:56 UTC, g4s8 commented on src/main/ruby/info.rb
> +        deps.each do |item|
What is the reason of making all these transformations in Ruby code? It's very hard to read for Java developers. It doesn't depend on any Ruby internals and could be easily moved to Java code

2021-08-02 07:56 UTC, g4s8 commented on src/main/java/com/artipie/gem/IRubyInfo.java
> + * An SDK, which servers gem packages.
Did you try to read your comments before committing changes?

2021-08-02 07:56 UTC, g4s8 commented on src/main/java/com/artipie/gem/IRubyInfo.java
> +public interface IRubyInfo {
What is the purpose of this interface?

2021-08-02 08:04 UTC, milkysoft commented on src/main/ruby/info.rb
> +        deps.each do |item|
@g4s8 , theoretically we can obtain some necessary properties for required output JSON with Java code, hovewer parts of required JSON values, such as name, version, authors, etc could be obtained only through utilising Ruby script in some way. Thus, natural implementation would be to obtain all required JSON values at one place, Ruby in this case.

2021-08-02 08:52 UTC, g4s8 commented on src/main/ruby/info.rb
> +        deps.each do |item|
> hovewer parts of required JSON values, such as name, version, authors, etc could be obtained only through utilising Ruby script in some way.

@milkysoft it's not true - in previous implementation (current base PR HEAD) it was possible to obtain any Ruby object attribute such as name, version, etc using Java code

2021-08-09 08:15 UTC, g4s8 commented
Closed by #116

2021-08-09 08:15 UTC, closed without merging