Issue #109 Delete temporarily saved gem after serving request
artipie/gem-adapter pull request #112
Opened 2021-08-02 13:07 UTC by milkysoft

2021-08-04 07:50 UTC, g4s8 requested changes
@milkysoft thanks, please check my comment

2021-08-04 07:50 UTC, g4s8 commented on src/main/java/com/artipie/gem/http/SubmitGemSlice.java
> +                    this.storage.delete(key);
`this.storage.delete(key);` is async call, we need to chain async calls, not just forget about it. Also, I'd change the key of this blob from `gems/<uuid>` to `_uploads/<uuid>` to indicate that it's a temporary upload prefix and not mix it with `gems`

2021-08-04 07:52 UTC, g4s8 commented
@milkysoft another comment about PR style: please don't forget to provide the description, and add links to the PR body, not title - title issue link does nothing, but description link creates a reference in GitHub between issue and PR. See https://github.com/artipie/artipie/blob/master/CONTRIBUTING.md

2021-08-05 05:06 UTC, milkysoft commented on src/main/java/com/artipie/gem/http/SubmitGemSlice.java
> +                    this.storage.delete(key);
@g4s8 , chaining implemented in latest commit.

Regarding changing directory, most probably indexing will not work if subdirectory has name other then `gems`. An idea is that Ruby indexing creates Ruby metadata in the current folder and Marshal subfolders with content for all gems stored in gems subfolder, not any other.

2021-08-06 09:06 UTC, g4s8 requested changes
@milkysoft the concurrency problem was not fixed

2021-08-06 09:06 UTC, g4s8 commented on src/main/java/com/artipie/gem/http/SubmitGemSlice.java
> +                .thenApply(none -> this.storage.delete(key))
It's still not fixed: `storage.delete(key)` returns future, method `thenApply` maps the result of previous call to lambda result. So you're just ignoring the result of `delete()` future. To fix it, use `thenCompose` instead of `thenApply`

2021-08-09 04:45 UTC, milkysoft commented on src/main/java/com/artipie/gem/http/SubmitGemSlice.java
> +                .thenApply(none -> this.storage.delete(key))
@g4s8 , Understood & agreed. `thenApply` is replaced withn `thenCompose` in latest commit

2021-08-09 08:20 UTC, g4s8 approved these changes
@milkysoft thanks

2021-08-09 08:21 UTC, merged