Use Java to create Gem info output JSON
artipie/gem-adapter pull request #116
Opened 2021-08-06 08:45 UTC by milkysoft

2021-08-06 12:12 UTC, g4s8 commented
@milkysoft why do we need a new pull request if we have #107 ?
This PR looks like a fixes for some review comments in #107 - so please, continue making changes in #107 and close this one to keep review history and to avoid noise in repository.

2021-08-09 11:32 UTC, g4s8 requested changes
@milkysoft please check a few comments. Also, don't forget to fix PR description and check review comments for previous PR, since some of them are the same

2021-08-09 11:32 UTC, g4s8 commented on src/main/java/com/artipie/gem/GemMeta.java
> +        T print(JsonObject data);
It's abstraction violation - this class is an intermediate layer for converting abstract gem data into concrete data format. Don't use json as parameter of this method. Please check review comments to previous PR for info response improvements, it was one of the major comment there

2021-08-09 11:32 UTC, g4s8 commented on src/main/java/com/artipie/gem/ruby/RubyGemMeta.java
> +            }
Why we can't just take **all** variables from spec metadata and render them into required format? Current implementation covers much more variables from spec metadata. In case if you need to filter out some attributes, you can just use some set as a filter for white-list or black-list attributes filtering.

2021-08-09 11:32 UTC, g4s8 commented on src/main/java/com/artipie/gem/ruby/RubyGemMeta.java
> +        final JsonObjectBuilder builder = Json.createObjectBuilder();
See previous comment: do not construct JSON on this abstraction layer

2021-08-09 11:32 UTC, g4s8 commented on src/main/java/com/artipie/gem/ruby/RubyGemMeta.java
> +                res = var.getValue().toString();
Why always a string? JSON has more types, rubygems uses numbers as well as strings, see https://guides.rubygems.org/rubygems-org-api/

2021-08-10 07:39 UTC, milkysoft commented on src/main/java/com/artipie/gem/ruby/RubyGemMeta.java
> +                res = var.getValue().toString();
@g4s8 , sure we will support all required types. This code uses `toString` method to return value from RubyVariable, it is possible to do only in String format. As alternative, we can consider independent Ruby interfaces which will read values from corresponding Ruby scripts

2021-08-10 07:41 UTC, milkysoft commented on src/main/java/com/artipie/gem/GemMeta.java
> +        T print(JsonObject data);
@g4s8 , I agree to add abstraction. The only change is that abstraction returns now Json tree instead of previously used Map

2021-08-10 07:52 UTC, milkysoft commented on src/main/java/com/artipie/gem/ruby/RubyGemMeta.java
> +            }
@g4s8 , this question relates to the following contradiction, so neither answer would be correct or incorrect. The task is to build output JSON which closely matches format from rubygems.org as in https://api.rubygems.org/api/v1/gems/gviz.json. This format contains values, which could be obtained through `Gem::Package.new('%s').spec`, but also a lot of other values, such as `sha` checksum, which should be obtained through other techniques. Also each value from `spec` should relates to specific key, which has custom logic, for example, while is `spec` there is `homepage` variable, output JSON should have `homepage_uri` JSON key at root.

2021-08-10 07:56 UTC, g4s8 commented on src/main/java/com/artipie/gem/ruby/RubyGemMeta.java
> +            }
@milkysoft I see, but why do we need to check each attribute name with this if-else block if we can but all of them to some set and check if set contains this variable or not?

2021-08-20 14:38 UTC, olenagerasimova requested changes
@milkysoft please, check my comments. Also, my main and general concern here is the lack of unit tests. All classes (`TreeNode`, `TreeNodeIter` and others) should be unit-tested. Not in this PR (it's already to big), but in the next one, when this one will be merged.

2021-08-20 14:38 UTC, olenagerasimova commented on src/main/java/com/artipie/gem/Gem.java
> +                            for (final TreeNode<ImmutablePair<String, String>> node : spec) {
`ImmutablePair` is `Pair` implementation, let's use higher abstraction (`Pair`) for variables, method return types etc and `ImmutablePair` when object creation is performed, e.g.:
```
for (final TreeNode<Pair<String, String>> node : spec) { ... }

Collection<Pair<String, String>> pairs = new ListOf<>(new ImmutablePair<>("left", "right"))
```

2021-08-20 14:38 UTC, olenagerasimova commented on src/main/java/com/artipie/gem/TreeNodeIter.java
> +@SuppressWarnings("PMD.NullAssignment")
this suppression seems unnecessary

2021-08-25 12:19 UTC, milkysoft commented on src/main/java/com/artipie/gem/Gem.java
> +                            for (final TreeNode<ImmutablePair<String, String>> node : spec) {
@olenagerasimova , the problem is the following: Pair is an abstract, cannot be instantiated, so you propose to instantiate ImmutablePairs, correct. But we use TreeNode<ImmutablePair>, not List.

if we replace ImmutablePair with Pair in:
`T print(TreeNode<ImmutablePair<String, String>> data);`


then in RubyGemMeta, where we instantiate ImuutablePair https://github.com/milkysoft/gem-adapter/blob/796f22e5824233862bfcf3cf21fd8ff2cf8d2e96/src/main/java/com/artipie/gem/ruby/RubyGemMeta.java#L141:

`return fmt.print(root);`

wil not compile. Thus declarations should always correspond to implementations

2021-08-25 12:20 UTC, milkysoft commented on src/main/java/com/artipie/gem/TreeNodeIter.java
> +@SuppressWarnings("PMD.NullAssignment")
@olenagerasimova , agreed, fixed in latest commit

2021-08-30 11:48 UTC, olenagerasimova commented
@milkysoft thanks
@g4s8 all my concerns are fixed here, please, take a look/merge

2021-09-01 12:53 UTC, g4s8 requested changes
The code in this [blog post](https://berativ.com/data-structures-2/) is not published under any public license, we can't just take and use it in our project because it could lead to serious copyright problems.

2021-09-03 06:20 UTC, milkysoft commented
@g4s8 , as an alternative to the blog post link, we can consider taking the code from https://github.com/ctapmex/zkTreeUtil/tree/master/src/main/java/com/dobrunov/zktreeutil publicky available repository, right?

2021-09-06 08:53 UTC, g4s8 commented
@milkysoft please check #123 - I added new format interfaces for tree structure to support JSON and YAML formats there.

2021-09-23 14:35 UTC, closed without merging