Fix routes
artipie/gem-adapter pull request #121
Opened 2021-09-01 10:36 UTC by milkysoft

close #120 

Fix routes to return valid gem info.

2021-09-01 10:37 UTC, milkysoft commented
@g4s8 , this Pull request is very easy and urgent

2021-09-03 07:50 UTC, kirill-h5i requested changes
@milkysoft please check my comment

2021-09-03 07:50 UTC, kirill-h5i commented on src/main/java/com/artipie/gem/http/ApiGetSlice.java
> +    public static final Pattern PATH_PATTERN = Pattern.compile("/api/v1/gems/(.+).(json|yml)");
Why to accept any symbol if we need only `-` here?

2021-09-08 19:01 UTC, g4s8 approved these changes
@milkysoft thanks

2021-09-09 08:19 UTC, merged