refactoring(test): refactored gem integration test
artipie/gem-adapter pull request #130
Opened 2021-09-29 11:51 UTC by g4s8

Extracted `setUp` and `tearDown` methods to extend test later.
Removed redundant temporary directory mounting, copy data to
container directly.
Removed empty log messages.

Ticket: #93

2021-09-29 12:07 UTC, olenagerasimova requested changes
@g4s8 please check my comments

2021-09-29 12:07 UTC, olenagerasimova commented on src/test/java/com/artipie/gem/GemCliITCase.java
> +            this.server.close();
As far as I remember, `close()` calls `stop()`, so there is no need to call both methods

2021-09-29 12:07 UTC, olenagerasimova commented on src/test/java/com/artipie/gem/GemCliITCase.java
> +        }
Same here

2021-09-29 12:07 UTC, olenagerasimova commented on src/test/java/com/artipie/gem/GemCliITCase.java
> +                    IOUtils.toByteArray(this.getClass().getResourceAsStream("/".concat(gem)))
Is not it possible to use `TestResourse` from asto and simplify the expression?

2021-09-30 07:47 UTC, g4s8 commented
@olenagerasimova thanks, fixed

2021-09-30 07:57 UTC, olenagerasimova approved these changes
@g4s8 thanks

2021-09-30 08:09 UTC, merged