Initial auth support
artipie/gem-adapter pull request #55
Opened 2020-08-17 14:17 UTC by Sammers21

Use base64 encrypted credentials as an API key.

Related to #45

2020-08-17 14:18 UTC, Sammers21 commented
@g4s8, review the PR, please.

2020-08-18 08:21 UTC, Sammers21 commented
@olegmoz, the Pull Request already includes 107 lines of changes. Does it make sense for you to create a test in another PR just for keeping the PR small?

2020-08-18 08:29 UTC, olegmoz commented
@Sammers21 I think even with test the PR is not going to be too big. You also may cut out `GemSlice` changes if you feel that with tests the PR becomes too complex

2020-08-18 08:40 UTC, Sammers21 commented
@olegmoz, so I should create 3 Pull Requests: one with GemSlice changes, second with `ApiKeySlice` changes and the last one with a test?

2020-08-18 09:00 UTC, olegmoz commented
@Sammers21 I never said that you need to split the PR into 3 parts. I think that it won't become too complex if you add basic tests to it. If you think that PR becomes too big when tests are added, then you may cut out some functionality into another PR.

2020-08-18 09:03 UTC, Sammers21 commented
@olegmoz, good. I will add a test to this PR.

2020-08-18 13:24 UTC, Sammers21 commented
@olegmoz, done. Can you review please?

2020-08-18 14:02 UTC, olegmoz commented on src/main/java/com/artipie/gem/GemSlice.java
> +        final Permissions perms,
@Sammers21 sorry for not noticing this first time around, but there is no point to pass `Permissions` to `GemSlice` as they are not used. You may add them later when implementing auth. `PMD.UnusedFormalParameter` warning suppression may also be removed

2020-08-18 14:03 UTC, olegmoz commented on src/main/java/com/artipie/gem/GemSlice.java
> +                ),
@Sammers21 this code remains untested

2020-08-18 14:07 UTC, Sammers21 commented
@g4s8, can you review the PR, please?

2020-08-18 14:07 UTC, olegmoz commented on src/main/java/com/artipie/gem/ApiKeySlice.java
> +            response = new RsWithStatus(RsStatus.FORBIDDEN);
@Sammers21 are you sure that forbidden is right code for this case? I am pretty sure that unauthorized answer is correct one for cases when authorization header is not provided. See https://tools.ietf.org/html/rfc7617

2020-08-18 14:08 UTC, olegmoz commented on src/main/java/com/artipie/gem/ApiKeySlice.java
> +            response = new RsWithStatus(RsStatus.FORBIDDEN);
@Sammers21 I'd suggest to test this code branch as well

2020-08-18 14:13 UTC, olegmoz commented on src/test/java/com/artipie/gem/ApiKeyTest.java
> + * @since 0.2
@Sammers21 `@since` tag is off, should be `0.3`

2020-08-18 14:13 UTC, olegmoz commented on src/test/java/com/artipie/gem/ApiKeyTest.java
> + * @checkstyle StringLiteralsConcatenationCheck (500 lines)
@Sammers21 this suppression is not needed

2020-08-18 14:16 UTC, olegmoz commented on src/test/java/com/artipie/gem/ApiKeyTest.java
> +        headers.add(new Authorization(String.format("Basic %s", token)));
@Sammers21 you may use convinient `Headers.From` class to create headers with single header. Also there is `Authorization.Basic` class to create basic auth header.

2020-08-18 14:20 UTC, Sammers21 commented on src/main/java/com/artipie/gem/GemSlice.java
> +        final Permissions perms,
@olegmoz, they might be used later. The field is for "not breaking a contract" in the future.

2020-08-18 14:23 UTC, Sammers21 commented on src/main/java/com/artipie/gem/ApiKeySlice.java
> +            response = new RsWithStatus(RsStatus.FORBIDDEN);
@olegmoz, я использую то же что использует AuthSlice.

2020-08-18 14:26 UTC, Sammers21 commented on src/test/java/com/artipie/gem/ApiKeyTest.java
> +        headers.add(new Authorization(String.format("Basic %s", token)));
@olegmoz, Я знаю об этом. Я специально использую именно так. Чтобы не добавлять лишней сложности в виде кодирования/декодирования в base64.

2020-08-18 14:28 UTC, Sammers21 commented on src/main/java/com/artipie/gem/GemSlice.java
> +                ),
@olegmoz, пофиксил

2020-08-18 14:29 UTC, Sammers21 commented on src/main/java/com/artipie/gem/ApiKeySlice.java
> +            response = new RsWithStatus(RsStatus.FORBIDDEN);
@olegmoz, это будет уже слишком много для "маленького" пул ревеста. Давать это смержим хоть что-то что минимально работает и протестировано а не упарываться в 100% кавередж.

2020-08-18 16:53 UTC, olegmoz commented on src/main/java/com/artipie/gem/GemSlice.java
> +        final Permissions perms,
@Sammers21 it is unrelated to the task at hand (poviding tokens), so there is no point to have it in this PR

2020-08-18 16:56 UTC, olegmoz commented on src/main/java/com/artipie/gem/ApiKeySlice.java
> +            response = new RsWithStatus(RsStatus.FORBIDDEN);
@Sammers21 please take a better look at code in https://github.com/artipie/http/blob/master/src/main/java/com/artipie/http/auth/SliceAuth.java

`FORBIDDEN` is returned when permission is not granted. The slice returns `UNAUTHORIZED` when auth header is not present or user cannot be authenticated

2020-08-18 16:58 UTC, olegmoz commented on src/test/java/com/artipie/gem/ApiKeyTest.java
> +        headers.add(new Authorization(String.format("Basic %s", token)));
@Sammers21 `Authorization.Basic(String)` creates a header with specified token, no encoding/decoding involved. It just to avoid `String.format("Basic %s", token)` code. And why don't you want to use `Headers.From` class? It makes code less verbose

2020-08-18 17:06 UTC, olegmoz commented on src/main/java/com/artipie/gem/ApiKeySlice.java
> +            response = new RsWithStatus(RsStatus.FORBIDDEN);
@Sammers21 the PR is not the large. I think that it worth testing if it part of contract and this kind of response expected by GEM client.

2020-08-18 17:08 UTC, olegmoz commented
@Sammers21 please see the answers

2020-08-18 17:45 UTC, Sammers21 commented on src/main/java/com/artipie/gem/GemSlice.java
> +        final Permissions perms,
@olegmoz, это контракт. Параметр будет использовать позже.

2020-08-18 17:53 UTC, Sammers21 commented on src/test/java/com/artipie/gem/ApiKeyTest.java
> +        headers.add(new Authorization(String.format("Basic %s", token)));
@olegmoz, не вижу такой опции даже в последней верисии:

![image](https://user-images.githubusercontent.com/16746106/90547811-b9fd0e00-e194-11ea-9762-de226d5ab1ea.png)

> Authorization.Basic(String)

2020-08-18 17:54 UTC, Sammers21 commented on src/test/java/com/artipie/gem/ApiKeyTest.java
> +        headers.add(new Authorization(String.format("Basic %s", token)));
Ну потому что мне ручками нужно будет все писать все строки? А так оно хоть как-то type-safe'ней

> And why don't you want to use Headers.From class? It makes code less verbose

2020-08-18 18:03 UTC, Sammers21 commented on src/main/java/com/artipie/gem/ApiKeySlice.java
> +            response = new RsWithStatus(RsStatus.FORBIDDEN);
@olegmoz, я думаю что это уже слишком, но сделал.

2020-08-18 18:05 UTC, Sammers21 commented
@olegmoz, посмотри пожалуйста пул реквест еще раз.

2020-08-19 06:44 UTC, g4s8 commented
@Sammers21 please use English for Github discussions

2020-08-19 07:40 UTC, olegmoz commented on src/main/java/com/artipie/gem/GemSlice.java
> +        final Permissions perms,
@Sammers21 I do not see what do you mean by "contract" here. This parameter is not required to generate the token. It may be added later as necessary.

2020-08-19 07:43 UTC, Sammers21 commented on src/main/java/com/artipie/gem/GemSlice.java
> +        final Permissions perms,
@olegmoz, ну чтобы генерировать ключ - не нужно, а чтобы давать доступ по ключу - нужно.

2020-08-19 07:44 UTC, olegmoz commented on src/test/java/com/artipie/gem/ApiKeyTest.java
> +        headers.add(new Authorization(String.format("Basic %s", token)));
@Sammers21 sorry about `Authorization.Basic` constructor, I was absolutely sure that it has option to pass token, my bad.

Regarding `Headers.From` usage I still do not see the problem here. You may write `new Headers.From(new Authorization(...))` and that's all

2020-08-19 07:50 UTC, olegmoz requested changes
@Sammers21 thanks for adding the test and fixing the return status. Please see my comments and answers

2020-08-19 07:50 UTC, olegmoz commented on src/test/java/com/artipie/gem/ApiKeyTest.java
> +    public void secondBranch() {
@Sammers21 that's not informative name for the test method, please improve

2020-08-19 07:50 UTC, olegmoz commented on src/test/java/com/artipie/gem/ApiKeyTest.java
> +        headers.add(new Authorization(String.format("Basic %s", token)));
@Sammers21 it's not really needed to pass headers in this test, so I'd suggest to remove them. Otherwise, please consider using `Headers.From` as well as in the other test

2020-08-19 08:09 UTC, Sammers21 commented
@olegmoz, посмотри пожалуйста пул реквест еще раз.

2020-08-19 09:28 UTC, olegmoz commented on src/main/java/com/artipie/gem/GemSlice.java
> +        final Permissions perms,
@Sammers21 that's right. But the PR is about API key generation, not checking permissions. So I am still convinced that `Permissions` should be removed from this PR and added later, when they are actually needed

2020-08-19 13:02 UTC, Sammers21 commented on src/main/java/com/artipie/gem/GemSlice.java
> +        final Permissions perms,
@olegmoz, Этот пул реквест меняет контракт между модулями. Я сторонник того чтобы менять эти контракты очень редко, а не в каждом коммите или "later". Если есть понимание того что оно точно будет нужно, то нужно это учитывать. Это моя принципиальная позиция.

2020-08-19 13:26 UTC, olegmoz requested changes
@Sammers21 thanks, please see just one minor comment

2020-08-19 13:26 UTC, olegmoz commented on src/main/java/com/artipie/gem/GemSlice.java
> +@SuppressWarnings({"PMD.UnusedPrivateField", "PMD.SingularField", "PMD.UnusedFormalParameter"})
@Sammers21 this suppression is not required anymore

2020-08-19 13:28 UTC, olegmoz approved these changes
@Sammers21 thanks, approved

2020-08-19 13:42 UTC, Sammers21 commented
@g4s8, can we merge?

2020-08-20 06:41 UTC, merged

2020-08-20 07:00 UTC, 0crat commented
Job `gh:artipie/gem-adapter#55` is not assigned, can't get performer

<!-- https://www.0crat.com/footprint/CT2E6TK9B/732446a1-7afe-4b5d-a98b-dc417c9d982b, version: 0.54.5, hash: ${buildNumber} -->