Endpoint support auth with permissions
artipie/gem-adapter pull request #59
Opened 2020-08-27 11:47 UTC by Sammers21

Closes #45

2020-08-27 11:48 UTC, Sammers21 commented
@olegmoz, review the PR please.

2020-08-27 13:01 UTC, olegmoz requested changes
@Sammers21 thanks, please see the comments. It's mostly about lack of tests coverage for the PR. Also there is no integration test to ensure that auth actually works.

2020-08-28 07:50 UTC, Sammers21 commented
@olegmoz, review the PR once again, please.

2020-08-28 07:53 UTC, Sammers21 commented on src/main/java/com/artipie/gem/GemApiKeyIdentity.java
> +    }
@olegmoz, should not.

2020-08-28 07:54 UTC, Sammers21 commented on src/main/java/com/artipie/gem/GemApiKeyIdentity.java
> +public final class GemApiKeyIdentity implements Identities {
@olegmoz, covered with existed tests.

2020-08-28 07:57 UTC, Sammers21 commented on src/main/java/com/artipie/gem/GemApiKeyIdentity.java
> +    }
Proof: 
![image](https://user-images.githubusercontent.com/16746106/91536338-3f16be80-e91d-11ea-80a8-a208907baa36.png)

2020-08-28 08:58 UTC, olegmoz approved these changes
@Sammers21 thanks, all is good

2020-08-28 08:58 UTC, merged

2020-08-28 09:00 UTC, Sammers21 commented
@rultor, release tag=`0.4`

2020-08-28 09:01 UTC, rultor commented
> @rultor, release tag=`0.4`

@sammers21 OK, I will release it now. Please check the progress [here](https://www.rultor.com/t/23140-682413012)

2020-08-28 09:10 UTC, rultor commented
> @rultor, release tag=`0.4`

@sammers21 Done! FYI, the full log is [here](https://www.rultor.com/t/23140-682413012) (took me 9min)

2020-08-28 09:20 UTC, 0crat commented
Job `gh:artipie/gem-adapter#59` is not assigned, can't get performer

<!-- https://www.0crat.com/footprint/CT2E6TK9B/97b5be80-d184-4f20-9c9b-3fdab10da08d, version: 0.54.5, hash: ${buildNumber} -->