Use random name for temp dir
artipie/gem-adapter pull request #77
Opened 2020-09-28 13:41 UTC by Sammers21

Closes #76

2020-09-28 14:01 UTC, olegmoz requested changes
@Sammers21 thanks, please see some comments

2020-09-28 14:15 UTC, Sammers21 commented on src/main/java/com/artipie/gem/GemSlice.java
> +        );
@olegmoz, Bad decision performance wise. Index update would not be incremental.

2020-09-28 14:16 UTC, Sammers21 commented on src/main/java/com/artipie/gem/GemSlice.java
> +                        ),
@olegmoz, this pr is not related to the problem of concurrent submission.

2020-09-28 14:16 UTC, Sammers21 commented on src/main/java/com/artipie/gem/GemSlice.java
> +        );
@olegmoz, does not work with createTempDir for unknown reasons

2020-09-28 15:23 UTC, olegmoz commented on src/main/java/com/artipie/gem/GemSlice.java
> +        );
@Sammers21 directory is created on every request this way, so everything will be lost between requests anyway

2020-09-28 15:23 UTC, olegmoz commented on src/main/java/com/artipie/gem/GemSlice.java
> +                        ),
@Sammers21 then please add tests to verify problem this PR solves

2020-09-28 15:25 UTC, olegmoz commented on src/main/java/com/artipie/gem/GemSlice.java
> +        );
@Sammers21 please investigate what is the problem with temp directory, because otherwise we store our files in a place user does not expect to be polluted with temporary data

2020-09-28 15:32 UTC, Sammers21 commented on src/main/java/com/artipie/gem/GemSlice.java
> +                        ),
@olegmoz, it is hard to create a test.

2020-09-28 15:32 UTC, Sammers21 commented on src/main/java/com/artipie/gem/GemSlice.java
> +        );
@olegmoz, done

2020-09-29 07:36 UTC, olegmoz requested changes
@Sammers21 thanks, please see the comments

2020-09-29 07:36 UTC, olegmoz commented on src/main/java/com/artipie/gem/GemSlice.java
> +            "default"
@Sammers21 no sure that's a great idea to allow creating `GemSlice` with default repo name. User should specify name explicitly to avoid storing data in same directory

2020-09-29 07:36 UTC, olegmoz commented on src/main/java/com/artipie/gem/GemSlice.java
> +                        ),
@Sammers21 this code needs to be tested. Otherwise we cannot be sure that changes fix the issue

2020-09-29 07:36 UTC, olegmoz commented on src/main/java/com/artipie/gem/GemSlice.java
> +        );
@Sammers21 I'd suggest to remove this code for directory cleanup, it does not make any sense to clean the directory on application exit. If it is saved between requests then why not save it between application restarts

2020-09-29 09:18 UTC, Sammers21 commented on src/main/java/com/artipie/gem/GemSlice.java
> +                        ),
@olegmoz, hard to test

2020-09-29 12:11 UTC, olegmoz requested changes
@Sammers21 thanks for changes, please see one comment. Also please note that test for the problem solved is mandatory.

2020-09-30 12:20 UTC, Sammers21 commented
@olegmoz, review the PR one more time, please.

2020-09-30 12:43 UTC, olegmoz requested changes
@Sammers21 thanks, please see the comments

2020-09-30 12:43 UTC, olegmoz commented on src/test/java/com/artipie/gem/GemCliITCase.java
> +    public void gemPushAndInstallWorks(@TempDir final Path temp)
@Sammers21 I'd suggest to create separate test method instead of making changes to existing one. Otherwise existing test case becomes over-complicated and it will be hard to detect problems with basic functionality in it

2020-09-30 12:43 UTC, olegmoz commented on src/test/java/com/artipie/gem/GemCliITCase.java
> +@SuppressWarnings({"PMD.ExcessiveMethodLength", "PMD.AvoidDuplicateLiterals"})
@Sammers21 this `ExcessiveMethodLength` warning is fair, please do not suppress it. The method in the test is way too big and may be simplified by extracting some duplicated code into methods. For example you may consider extracting code for server staring or pushing gems

2020-09-30 12:43 UTC, olegmoz commented on src/test/java/com/artipie/gem/GemCliITCase.java
> +        );
@Sammers21 are you sure this check does fail when single directory is used for both `GemSlice` instances? Because `builder` was present in index, but the `.gem` file was still missing. So to me it seems that this check does not really tests what we need

2020-09-30 12:44 UTC, Sammers21 commented on src/test/java/com/artipie/gem/GemCliITCase.java
> +    public void gemPushAndInstallWorks(@TempDir final Path temp)
@olegmoz, the separated test would look the same as this.

2020-09-30 12:45 UTC, Sammers21 commented on src/test/java/com/artipie/gem/GemCliITCase.java
> +@SuppressWarnings({"PMD.ExcessiveMethodLength", "PMD.AvoidDuplicateLiterals"})
@olegmoz, it's an integration test, it can be  too big

2020-09-30 12:45 UTC, Sammers21 commented on src/test/java/com/artipie/gem/GemCliITCase.java
> +        );
@olegmoz, look to the test log. It does.

2020-09-30 12:46 UTC, Sammers21 commented
@olegmoz, review the PR one more time, please.

2020-09-30 12:48 UTC, Sammers21 commented on src/test/java/com/artipie/gem/GemCliITCase.java
> +        );
@olegmoz, when the same dir used, the check fail

2020-09-30 12:49 UTC, olegmoz commented
@Sammers21 your replies do not really answer my questions. Please make required changes or elaborate your answers

2020-09-30 12:50 UTC, Sammers21 commented
@olegmoz, Почему не отвечают? Я же на все ответил. Ну пиши пожалуйста на русском если я на английском не понимаю.

2020-09-30 12:54 UTC, Sammers21 commented
@olegmoz, на какой конкретно я не ответил?

2020-09-30 13:42 UTC, closed without merging

2020-10-06 00:58 UTC, 0crat commented
Pull request [#77](https://github.com/artipie/gem-adapter/issues/77) was not merged, no payment for `ARC`, see [§28](http://www.zerocracy.com/policy.html#28)

<!-- https://www.0crat.com/footprint/CT2E6TK9B/281fd54f-79f0-4145-806a-6fd2dffe5352, version: 0.54.5, hash: ${buildNumber} -->