WIP: Implement merge metadata
artipie/gem-adapter pull request #88
Opened 2021-04-06 07:51 UTC by milkysoft

2021-04-06 14:41 UTC, g4s8 commented
@milkysoft please see contributing guides and format PR properly: https://github.com/artipie/artipie/blob/master/CONTRIBUTING.md

2021-04-07 07:38 UTC, olenagerasimova commented
@milkysoft please format this PR properly, as suggested in the contribution guide, I will not review the PR until you do

2021-04-07 07:39 UTC, olenagerasimova commented
@milkysoft also please update testcontainers to `1.15.2`, it will fix the issue with IT in the actions

2021-04-07 08:53 UTC, olenagerasimova commented
@milkysoft please, fix all the complaints from `qulice`, there are 40 violations

2021-04-07 12:04 UTC, g4s8 commented
@milkysoft please see CI report, it contains some errors: https://github.com/artipie/gem-adapter/pull/88/checks?check_run_id=2285901020

To make sure CI passes successfully you can run `mvn -B clean verify -Pqulice` locally before pushing to GitHub

2021-04-07 12:10 UTC, g4s8 commented on src/main/java/com/artipie/gem/GemBean.java
> +public class GemBean {
@milkysoft I think `Gem` is a better name here, since it's not a bean in terms of Java beans

2021-04-07 12:11 UTC, g4s8 commented on src/main/java/com/artipie/gem/GemBean.java
> +    public Completable update(final String key) {
@milkysoft I'd recommend using `CompletionStage<Void>` here as standard Java API, see https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CompletionStage.html

2021-04-07 12:11 UTC, g4s8 commented on src/main/java/com/artipie/gem/GemBean.java
> +    public Completable update(final Key key) {
@milkysoft same here

2021-04-07 12:11 UTC, g4s8 commented on src/main/java/com/artipie/gem/GemBean.java
> +    public Completable batchUpdate(final Key prefix) {
@milkysoft same here

2021-04-07 12:11 UTC, g4s8 commented on src/main/java/com/artipie/gem/GemBean.java
> +    }
@milkysoft this method is not relevant for Gem repository

2021-04-07 12:12 UTC, g4s8 commented on src/main/java/com/artipie/gem/GemBean.java
> +    public static Slice rubyLookUp(final String rclass,
@milkysoft we don't need HTTP layer (`Slice` implementation) for metadata update SDK

2021-04-07 12:13 UTC, g4s8 commented on src/main/java/com/artipie/gem/GemSlice.java
> +    public static RubyRuntimeAdapter getEvaler(Ruby runtime) {
@milkysoft I'd refactor Gem index update logic by moving it to `Gem` class and call this `Gem` from `Slice` implementation

2021-04-07 12:14 UTC, g4s8 commented on src/main/java/com/artipie/gem/GemsMerger.java
> +public interface GemsMerger {
@milkysoft what is the purpose if this interface?

2021-04-07 12:14 UTC, g4s8 commented on src/main/ruby/AstoIndexer.rb
> +#  For now, generated indexes are stored locally in repo directory.
@milkysoft please reverse `todo` changes, since they autogenerates GitHub tickets from such comments

2021-04-08 09:06 UTC, g4s8 requested changes
@milkysoft please check new comments

2021-04-08 09:06 UTC, g4s8 commented on src/main/java/com/artipie/gem/Gem.java
> +        res.join();
@milkysoft why blocking on async call?

2021-04-08 09:06 UTC, g4s8 commented on src/main/java/com/artipie/gem/Gem.java
> +    static Slice rubyUpdater(final String rclass, final Storage storage, final String repo,
@milkysoft we don't need a `Slice` for SDK updates (Slice is HTTP endpoint)

2021-04-08 09:06 UTC, g4s8 commented on src/main/ruby/AstoUpdater.rb
> +    puts "8768768768asd"
@milkysoft why to print this string?

2021-04-08 09:06 UTC, g4s8 commented on src/main/java/com/artipie/gem/Gem.java
> +            tmpdir = Files.createTempDirectory(prefix.string());
@milkysoft we need to remove temp directory after update (successful or failed)

2021-04-08 09:06 UTC, g4s8 commented on src/main/java/com/artipie/gem/Gem.java
> +        final CompletableFuture<Void> res = CompletableFuture.runAsync(
@milkysoft you can just use `return` here without creating a variable

2021-04-08 09:06 UTC, g4s8 commented on src/main/java/com/artipie/gem/Gem.java
> +            )
@milkysoft after update the temp dir, we need to upload it to `storage`, it can be done using `storage.save()`

2021-04-09 08:19 UTC, zorcheal commented on src/main/java/com/artipie/gem/GemsMerger.java
> +public interface GemsMerger {
@g4s8 , Proposed an interface to provide the method of merging metadata.

2021-04-09 08:25 UTC, zorcheal commented on src/main/ruby/AstoUpdater.rb
> +    puts "8768768768asd"
@g4s8 , removed test string

2021-04-09 08:26 UTC, zorcheal commented on src/main/java/com/artipie/gem/Gem.java
> +        final CompletableFuture<Void> res = CompletableFuture.runAsync(
@g4s8 , agreed

2021-04-14 06:40 UTC, g4s8 requested changes
@milkysoft please see my comments

2021-04-14 06:40 UTC, g4s8 commented on src/main/java/com/artipie/gem/Gem.java
> +                Gem.class.getResourceAsStream("/AstoUpdater.rb"),
@milkysoft two comments here:
 - it'd be more correct to load the resource using thread context class-loader, not this class class-loader: `Thread.currentThread().getContextClassLoader().getResourceAsStream("...")`; see: https://stackoverflow.com/a/40303723/1723695
 - let's avoid IO operations in constructor, since's constructor is supposed to be light-weight and fast to invoke, where resource loading and Ruby script evaluating is a resource-consuming operation. It could be moved to some lazy-evaluating code which invokes this script on demand.

2021-04-14 06:40 UTC, g4s8 commented on src/main/java/com/artipie/gem/Gem.java
> +        }
@milkysoft temp dir creation could be moved to async operation too with `CompletableFuture.runAsync(() -> {})`

2021-04-14 06:40 UTC, g4s8 commented on src/main/java/com/artipie/gem/Gem.java
> +    }
@milkysoft we can avoid having separate script file for indexer and use `RubyRuntimeAdapter` instead:
 1. Create a state of `Ruby` and initialize it on first call with needed `require`s
 2. Call `RubyRuntimeAdapter` `eval("Gem::Indexer.new('%s').generate_index`

Then we can remove all these script files and use plain adapter instead

2021-04-14 06:40 UTC, g4s8 commented on src/main/java/com/artipie/gem/GemIndexer.java
> +public interface GemIndexer {
@milkysoft If we use plain `RubyRuntimeAdapter` with `eval` we don't need this interface

2021-04-14 06:40 UTC, g4s8 commented on src/main/java/com/artipie/gem/GemSlice.java
> +    /**
@milkysoft let's avoid any changes in `GemSlice` for now, we can refactor it later, since it's out of scope now

2021-04-14 06:40 UTC, g4s8 commented on src/main/java/com/artipie/gem/GemsMerger.java
> +public interface GemsMerger {
@milkysoft if we use `RubyRuntimeAdapter` we can remove this interface

2021-04-14 06:40 UTC, g4s8 commented on src/main/java/com/artipie/gem/RubyIndexer.java
> +public class RubyIndexer implements GemIndexer {
@milkysoft and same here

2021-04-15 12:56 UTC, g4s8 requested changes
@milkysoft please see my comments. Pay attention: we're exposing public SDK for developers, so the Javadoc is an important part of this SDK which is describing API and usage, so it should be accurate enough.

Also, please check a few previous comments and suggestions.

2021-04-15 12:56 UTC, g4s8 commented on src/main/java/com/artipie/gem/Gem.java
> +public class Gem {
@milkysoft this class could be `final`

2021-04-15 12:56 UTC, g4s8 commented on src/main/java/com/artipie/gem/Gem.java
> +    public CompletionStage<Void> batchUpdate() {
@milkysoft we need to specify the `Key` parameter of repository location

2021-04-15 12:56 UTC, g4s8 commented on src/main/java/com/artipie/gem/Gem.java
> +     * Lookup an instance of slice, implemented with JRuby.
@milkysoft I didn't get this documentation

2021-04-15 12:56 UTC, g4s8 commented on src/main/java/com/artipie/gem/Gem.java
> +     * Lookup an instance of slice, implemented with JRuby.
@milkysoft and same here

2021-04-15 12:56 UTC, g4s8 commented on src/main/java/com/artipie/gem/Gem.java
> +     * Primary storage.
@milkysoft it's not a storage

2021-04-15 12:56 UTC, g4s8 commented on src/main/java/com/artipie/gem/Gem.java
> +     * Primary storage.
@milkysoft it's not a storage

2021-04-15 12:56 UTC, g4s8 commented on src/main/java/com/artipie/gem/Gem.java
> + * @since 0.1
@milkysoft the current version of gem-adapter is `0.6`, so according to semver the next version with breaking changes should be `1.0`

2021-04-15 12:56 UTC, g4s8 commented on src/main/java/com/artipie/gem/Gem.java
> +     * Primary storage.
@milkysoft do we have secondary? I'd say registry storage or repository storage

2021-04-15 12:56 UTC, g4s8 commented on src/main/java/com/artipie/gem/Gem.java
> +     * @param key The name of a slice class, implemented in JRuby.
@milkysoft what is the name of a slice?

2021-04-15 12:56 UTC, g4s8 commented on src/main/java/com/artipie/gem/Gem.java
> +                    final FileStorage remote = new FileStorage(tmpdir);
@milkysoft I'd call it `local`, since remote storage is `this.storage` logically

2021-04-15 12:56 UTC, g4s8 commented on src/main/java/com/artipie/gem/Gem.java
> +                    return Single.fromFuture(this.storage.list(Key.ROOT))
@milkysoft here we should use `Key` parameter passed as method argument. I'd recommend wrapping `this.storage` with `new SubStorage(key, this.storage)` to avoid manual keys and paths composition

2021-04-15 12:56 UTC, g4s8 commented on src/main/java/com/artipie/gem/Gem.java
> +                    () -> rubyUpdater(tmpdir.toString())
@milkysoft since we're ignoring the result of `rubyUpdater`, then we can return `void` from `rubyUpdater`

2021-04-15 12:56 UTC, g4s8 commented on src/main/java/com/artipie/gem/Gem.java
> +                    final FileStorage remote = new FileStorage(tmpdir);
@milkysoft and same here: it's local storage

2021-04-15 12:56 UTC, g4s8 commented on src/main/java/com/artipie/gem/Gem.java
> +                                    .thenCompose(content -> this.storage.save(key, content))
@milkysoft and here: we either need to compose keys manually or wrap it with `new SubStorage(key, this.storage)`

2021-04-15 12:56 UTC, g4s8 commented on src/main/java/com/artipie/gem/Gem.java
> +            .thenCompose(
@milkysoft it should be `.handle()`, not `thenCompose`, since we need to remove tmp-dir not only on success scenario but on error too

2021-04-15 12:56 UTC, g4s8 commented on src/main/ruby/AstoUpdater.rb
> +require 'rubygems/indexer.rb'
@milkysoft it seems we don't need this file too, since we're using evaler directly

2021-04-15 13:11 UTC, 0crat commented
@g4s8[/z](https://www.0crat.com/u/g4s8) I see that you unassigned this issue; the order is still assigned to @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) though; to cancel the order use `refuse`, as in [§6](http://www.zerocracy.com/policy.html#6)

<!-- https://www.0crat.com/footprint/CT2E6TK9B/c925cd6d-90ff-4770-af0e-108b6ee2c465, version: 0.55.1, hash: ${buildNumber} -->

2021-04-16 11:49 UTC, g4s8 requested changes
@milkysoft please see a few comments

2021-04-16 11:49 UTC, g4s8 commented on src/main/java/com/artipie/gem/Gem.java
> +                    return Files.createTempDirectory(prefix.string());
@milkysoft why `prefix.string()` here? It could be `"gem"`

2021-04-16 11:49 UTC, g4s8 commented on src/main/java/com/artipie/gem/Gem.java
> +        }
@milkysoft it's not correct - we need to re-throw exception here.

2021-04-16 11:49 UTC, g4s8 commented on src/main/java/com/artipie/gem/RubyIndexer.java
> +public final class RubyIndexer implements GemIndexer {
@milkysoft this class could be removed too

2021-04-16 11:49 UTC, g4s8 commented on src/test/java/com/artipie/gem/SubmitGemITCase.java
> +    @Test
@milkysoft let's move it to `GemITCase` class

2021-04-16 12:00 UTC, g4s8 commented on src/main/java/com/artipie/gem/GemsMerger.java
> +public interface GemsMerger {
So it could be removed now

2021-04-16 12:21 UTC, milkysoft commented on src/test/java/com/artipie/gem/SubmitGemITCase.java
> +    @Test
@g4s8 , done

2021-04-16 12:22 UTC, milkysoft commented on src/main/java/com/artipie/gem/RubyIndexer.java
> +public final class RubyIndexer implements GemIndexer {
@g4s8 , done

2021-04-16 12:22 UTC, milkysoft commented on src/main/java/com/artipie/gem/Gem.java
> +        }
@g4s8 , done

2021-04-16 12:22 UTC, milkysoft commented on src/main/java/com/artipie/gem/Gem.java
> +                    return Files.createTempDirectory(prefix.string());
@g4s8 , done

2021-04-16 12:22 UTC, milkysoft commented on src/main/ruby/AstoUpdater.rb
> +require 'rubygems/indexer.rb'
@g4s8 , done

2021-04-16 13:06 UTC, g4s8 requested changes
@milkysoft please see a few comments

2021-04-16 13:06 UTC, g4s8 commented on src/test/java/com/artipie/gem/GemITCase.java
> +            (CompletableFuture<Void>) gem.batchUpdate(new Key.From(prefix));
@milkysoft class casting is not really a good practice since it introduces additional coupling in code (e.g. we may change implementation of `CompletionStage<>` later), you can use this code instead:
```java
gem.batchUpdate(new Key.From(prefix))
  .toCompletionStage().join();
```

2021-04-16 13:06 UTC, g4s8 commented on src/test/java/com/artipie/gem/GemITCase.java
> +                .forEach(filename -> files.add(filename.toString()));
@milkysoft you can simplify it to:
```java
final List<String> files = Files.walk(repo).map(Path::toString).collect(Collectors.toList());
```

2021-04-18 13:32 UTC, milkysoft commented on src/main/java/com/artipie/gem/Gem.java
> +final public class Gem {
@g4s8 , `Gem` class is public, it is just requirements of PMD/qulice tool to set consequence of declaration in exactly this order: `final public class Gem` instead of `public final class Gem`

2021-04-18 13:33 UTC, milkysoft commented on src/main/java/com/artipie/gem/Gem.java
> +            throw new CompletionException(err);
@g4s8 , done

2021-04-18 13:33 UTC, milkysoft commented on src/test/java/com/artipie/gem/GemITCase.java
> +                .forEach(filename -> files.add(filename.toString()));
@g4s8 , done

2021-04-18 13:34 UTC, milkysoft commented on src/test/java/com/artipie/gem/GemITCase.java
> +            (CompletableFuture<Void>) gem.batchUpdate(new Key.From(prefix));
@g4s8 , done

2021-04-19 07:04 UTC, g4s8 requested changes
@milkysoft please see a few minor issues

2021-04-19 07:04 UTC, g4s8 commented on src/main/java/com/artipie/gem/Gem.java
> + * @checkstyle ParameterNumberCheck (500 lines)
@milkysoft this suppression could be removed after refactoring

2021-04-19 07:04 UTC, g4s8 commented on src/test/java/com/artipie/gem/GemITCase.java
> + * @checkstyle StringLiteralsConcatenationCheck (500 lines)
@milkysoft this warning means that `String.format()` could be used instead of concatenations, since it's considered as more readable

2021-04-19 07:04 UTC, g4s8 commented on src/test/java/com/artipie/gem/GemITCase.java
> +@SuppressWarnings("PMD.SystemPrintln")
@milkysoft I don't see any `print*()` calls, so this suppression could be removed

2021-04-19 08:33 UTC, milkysoft commented on src/test/java/com/artipie/gem/GemITCase.java
> +@SuppressWarnings("PMD.SystemPrintln")
@g4s8 , done

2021-04-19 08:33 UTC, milkysoft commented on src/test/java/com/artipie/gem/GemITCase.java
> + * @checkstyle StringLiteralsConcatenationCheck (500 lines)
@g4s8 , done

2021-04-19 08:33 UTC, milkysoft commented on src/main/java/com/artipie/gem/Gem.java
> + * @checkstyle ParameterNumberCheck (500 lines)
@g4s8 , agreed, removed

2021-04-19 09:11 UTC, g4s8 approved these changes
@milkysoft thanks

2021-04-19 09:11 UTC, merged

2021-04-25 01:11 UTC, 0crat commented
@g4s8[/z](https://www.0crat.com/u/g4s8) resigned from [#88](https://github.com/artipie/gem-adapter/issues/88), since the job is not in scope anymore

<!-- https://www.0crat.com/footprint/CT2E6TK9B/e368b61b-fbff-4f32-80ec-09b769029176, version: 0.55.1, hash: ${buildNumber} -->