WIP: Rewrite slice implementation from ruby to java refactoring
artipie/gem-adapter pull request #92
Opened 2021-04-21 13:27 UTC by milkysoft

close #90

2021-04-22 13:29 UTC, g4s8 commented
@milkysoft please see https://github.com/artipie/artipie/blob/master/CONTRIBUTING.md#pull-request-style

2021-04-26 08:54 UTC, g4s8 commented
@milkysoft please make sure the CI is passing

2021-05-14 14:11 UTC, olenagerasimova requested changes
@milkysoft sorry for the delay, please, check some minor comments

2021-05-14 14:11 UTC, olenagerasimova commented on src/main/java/com/artipie/gem/SubmitGem.java
> + * @since 1.0
@milkysoft since tag value is incorrect

2021-05-14 14:11 UTC, olenagerasimova commented on src/main/java/com/artipie/gem/SubmitGem.java
> + * @checkstyle ParameterNumberCheck (500 lines)
@milkysoft these suppressions does not seem necessary

2021-05-14 14:11 UTC, olenagerasimova commented on src/main/java/com/artipie/gem/GemSlice.java
>   *  on first request.
@milkysoft this part of javadoc was part of the [puzzle](https://github.com/artipie/gem-adapter/issues/15) and does not seem valid now. Please, correct it to correspond current implementation or remove it.

2021-05-16 13:22 UTC, Sammers21 commented
This change is a step backwards in a direction of making the Ruby adapter independent from the local file system. The right way is to change `AstoIndexer.rb` in a way so it uses asto storage only without filesystem at all. It does not make any sense to replace the current implementation with a simplistic java wrapper that does not even support incremental update and generate index every time from the scratch. And I'd also warn you that the implementation you are trying to switch will not work as good or might be not working at all.

2021-05-17 05:41 UTC, g4s8 requested changes
@milkysoft please check my comments

2021-05-17 05:41 UTC, g4s8 commented on src/main/java/com/artipie/gem/SubmitGem.java
> +            ).thenCompose(none -> this.gem.batchUpdate(new Key.From("TestKey")))
`TestKey` seems to be a typo

2021-05-17 05:41 UTC, g4s8 commented on src/test/java/com/artipie/gem/GemCliITCase.java
> +        Files.copy(Paths.get("./src/test/resources/test/gems/builder-3.2.4.gem"), builder);
I'd suggest getting rid of one time variables and use string literals instead. Also, accessing `./src/test` path is not a correct way of copying test resources, please use proper classloader methods. And finally, it could be grouped in a loop for better readability.

2021-05-18 02:03 UTC, Sammers21 commented
@g4s8 , it seems that you are not paying enough attention, but the adapter maximum scale will be 100 artifacts max with unreasonable update time like a few seconds. If you feel like you want to bury this adapter then of course merge this pull request.

2021-05-18 12:06 UTC, milkysoft commented on src/main/java/com/artipie/gem/SubmitGem.java
> +            ).thenCompose(none -> this.gem.batchUpdate(new Key.From("TestKey")))
@g4s8 , fixed in latest commit

2021-05-18 12:39 UTC, g4s8 requested changes
@milkysoft please see my comments

2021-05-18 12:39 UTC, g4s8 commented on src/main/java/com/artipie/gem/Gem.java
> +     * @param gem Location of repository
The javadoc is not correct here

2021-05-18 12:39 UTC, g4s8 commented on src/main/java/com/artipie/gem/Gem.java
> +        final Storage remote = this.storage;
This variable assignment is useless (just copy the reference)

2021-05-18 12:39 UTC, g4s8 commented on src/main/java/com/artipie/gem/Gem.java
> +        if (gem != null) {
`gem` we don't perform null-checking for internal code since Checkstyle won't allow returning null or null assignment.

2021-05-18 12:39 UTC, g4s8 commented on src/main/java/com/artipie/gem/Gem.java
> +            .filter(pair -> vars.contains(pair))
This `filter` method will reject `list` result if vars doesn't contain `pairs`; we need to filter out elements which are not part of both sets, in other words we need an intersection of key list with our metadata and gem:
result = list &cap; (metadata &cup; gem)

2021-05-18 12:39 UTC, g4s8 commented on src/main/java/com/artipie/gem/SubmitGem.java
> +            ).thenCompose(none -> this.gem.batchUpdate(Key.ROOT))
It should be gem key

2021-05-18 12:40 UTC, g4s8 commented
@milkysoft also, the CI seems to be broken

2021-05-20 10:09 UTC, milkysoft commented on src/main/java/com/artipie/gem/SubmitGem.java
> + * @since 1.0
@olenagerasimova , we agreed the next release will be 1.0, this is the first time this file will be included into release (together with GemIndex.java, Gem.java), thus 1.0 seems to be correct

2021-05-20 10:16 UTC, milkysoft commented on src/main/java/com/artipie/gem/SubmitGem.java
> + * @checkstyle ParameterNumberCheck (500 lines)
@olenagerasimova , thanks, fixed in latest [commit](https://github.com/artipie/gem-adapter/pull/92/commits/20d38eafac34381139e01f77472be20594c9bddb)

2021-05-20 10:17 UTC, milkysoft commented on src/main/java/com/artipie/gem/GemSlice.java
>   *  on first request.
@olenagerasimova , thanks, fixed in latest [commit](https://github.com/artipie/gem-adapter/pull/92/commits/20d38eafac34381139e01f77472be20594c9bddb)

2021-05-20 10:17 UTC, milkysoft commented on src/main/java/com/artipie/gem/Gem.java
> +     * @param gem Location of repository
@g4s8, thanks, fixed in latest [commit](https://github.com/artipie/gem-adapter/pull/92/commits/20d38eafac34381139e01f77472be20594c9bddb)

2021-05-20 10:17 UTC, milkysoft commented on src/main/java/com/artipie/gem/Gem.java
> +        final Storage remote = this.storage;
@g4s8 , thanks, fixed in latest [commit](https://github.com/artipie/gem-adapter/pull/92/commits/20d38eafac34381139e01f77472be20594c9bddb)

2021-05-20 10:18 UTC, milkysoft commented on src/main/java/com/artipie/gem/Gem.java
> +        if (gem != null) {
@g4s8 , thanks, fixed in latest [commit](https://github.com/artipie/gem-adapter/pull/92/commits/20d38eafac34381139e01f77472be20594c9bddb)

2021-05-20 10:18 UTC, milkysoft commented on src/main/java/com/artipie/gem/SubmitGem.java
> +            ).thenCompose(none -> this.gem.batchUpdate(Key.ROOT))
@g4s8, thanks, fixed in latest [commit](https://github.com/artipie/gem-adapter/pull/92/commits/20d38eafac34381139e01f77472be20594c9bddb)

2021-05-20 11:58 UTC, milkysoft commented on src/test/java/com/artipie/gem/GemCliITCase.java
> +        Files.copy(Paths.get("./src/test/resources/test/gems/builder-3.2.4.gem"), builder);
@g4s8 , thanks, fixed in latest [commit](https://github.com/artipie/gem-adapter/pull/92/commits/68b72b0e4f107d93f548b14923e9e1d170382d69)

2021-05-20 12:31 UTC, g4s8 requested changes
@milkysoft please check a few comments

2021-05-20 12:31 UTC, g4s8 commented on src/main/java/com/artipie/gem/Gem.java
> +                            || key.string().contains("quick/Marshal.4.8");
We can add this key to the set

2021-05-20 12:31 UTC, g4s8 commented on src/main/java/com/artipie/gem/Gem.java
> +        final Set<String> vars = new HashSet<>();
I'd rename this set to self-describing variable. And it could be places in a static field. To simplify constructing you can use `new HasSet<>(Arrays.asList("latest_specs.4.8", "latest_specs.4.8.gz", "etc.."))`

2021-05-20 12:31 UTC, g4s8 commented on src/main/java/com/artipie/gem/GemSlice.java
> + *  Ruby runtime initialization and Slice evaluation happens
What does this javadoc mean?

2021-05-20 12:31 UTC, g4s8 commented on src/test/java/com/artipie/gem/GemCliITCase.java
> +        while (iter.hasNext()) {
There could be simple `for (String resource : gems)`

2021-05-21 08:32 UTC, milkysoft commented on src/main/java/com/artipie/gem/Gem.java
> +        final Set<String> vars = new HashSet<>();
@g4s8 , thanks, fixed in latest [commit](https://github.com/artipie/gem-adapter/pull/92/commits/d6ec4b7678e9b8c28627464fa1d1d60842906fb1)

2021-05-21 08:32 UTC, milkysoft commented on src/main/java/com/artipie/gem/Gem.java
> +                            || key.string().contains("quick/Marshal.4.8");
@g4s8 , thanks, fixed in latest [commit](https://github.com/artipie/gem-adapter/pull/92/commits/d6ec4b7678e9b8c28627464fa1d1d60842906fb1)

2021-05-21 08:32 UTC, milkysoft commented on src/test/java/com/artipie/gem/GemCliITCase.java
> +        while (iter.hasNext()) {
@g4s8 , thanks, fixed in latest [commit](https://github.com/artipie/gem-adapter/pull/92/commits/d6ec4b7678e9b8c28627464fa1d1d60842906fb1)

2021-05-21 08:36 UTC, milkysoft commented on src/main/java/com/artipie/gem/GemSlice.java
> + *  Ruby runtime initialization and Slice evaluation happens
@g4s8, I changed to `HTTP Layer` in latest [commit](https://github.com/artipie/gem-adapter/pull/92/commits/a695fa360b5c951ade2ec13e0671e4e609898625)

2021-05-24 07:28 UTC, g4s8 approved these changes
@milkysoft thanks

2021-05-24 08:28 UTC, g4s8 commented
@olenagerasimova please approve if your comments were resolved

2021-05-24 08:31 UTC, olenagerasimova approved these changes
@milkysoft thanks

2021-05-24 08:31 UTC, merged