WIP: Issue #85 Implement GemInfo
artipie/gem-adapter pull request #94
Opened 2021-05-13 10:51 UTC by milkysoft

close #85

2021-05-14 11:29 UTC, g4s8 commented
@milkysoft please check our contributing style guide: https://github.com/artipie/artipie/blob/master/CONTRIBUTING.md

Pay attention to PR and commit message format

2021-05-14 12:28 UTC, olenagerasimova requested changes
@milkysoft please, check my comments. Also, this PR formatting does not correspond to [contribution guide](https://github.com/artipie/artipie/blob/master/CONTRIBUTING.md)

2021-05-14 12:28 UTC, olenagerasimova commented on src/main/java/com/artipie/gem/GemInfo.java
> +        Response response = new RsWithStatus(RsStatus.NOT_IMPLEMENTED);
@milkysoft there is no need to create and initialize this variable - `else` block of the `if` statement can be simply omitted and `Response` can be created right in the `return` statement in the `if` block.

2021-05-14 12:28 UTC, olenagerasimova commented on pom.xml
> +      <groupId>org.json</groupId>
@milkysoft we use `javax.json` in `artipie` and even have [`RsJson`](https://github.com/artipie/http/blob/master/src/main/java/com/artipie/http/rs/common/RsJson.java) you can use in the slice. Example usages of `javax.json` can be found in [test](https://github.com/artipie/http/blob/master/src/test/java/com/artipie/http/rs/common/RsJsonTest.java)

2021-05-14 12:28 UTC, olenagerasimova commented on src/test/java/com/artipie/gem/QueryGemITCase.java
> +public class QueryGemITCase {
@milkysoft is it really necessary to create IT for this slice? Seems like unit test can be added, we have [matcher](https://github.com/artipie/http/blob/master/src/main/java/com/artipie/http/hm/SliceHasResponse.java) to test slice behavior, example can be found [here](https://github.com/artipie/pypi-adapter/blob/master/src/test/java/com/artipie/pypi/http/SearchSliceTest.java)

2021-05-14 12:28 UTC, olenagerasimova commented on src/test/java/com/artipie/gem/QueryGemITCase.java
> + * @since 0.2
@milkysoft `since` tag value is incorrect, should be `0.7`

2021-05-14 12:28 UTC, olenagerasimova commented on src/test/java/com/artipie/gem/QueryGemITCase.java
> +            new IsEqual<>(Integer.parseInt(RsStatus.OK.code()))
@milkysoft I'd suggest also to check response body

2021-05-14 13:08 UTC, milkysoft commented on src/test/java/com/artipie/gem/QueryGemITCase.java
> +            new IsEqual<>(Integer.parseInt(RsStatus.OK.code()))
@olenagerasimova , fixed in latest commit

2021-05-14 13:08 UTC, milkysoft commented on src/test/java/com/artipie/gem/QueryGemITCase.java
> + * @since 0.2
@olenagerasimova , fixed in latest commit

2021-05-14 13:09 UTC, milkysoft commented on pom.xml
> +      <groupId>org.json</groupId>
@olenagerasimova , fixed in latest commit

2021-05-14 13:09 UTC, milkysoft commented on src/main/java/com/artipie/gem/GemInfo.java
> +        Response response = new RsWithStatus(RsStatus.NOT_IMPLEMENTED);
@olenagerasimova , fixed in latest commit

2021-05-17 09:49 UTC, milkysoft commented on src/test/java/com/artipie/gem/QueryGemITCase.java
> +public class QueryGemITCase {
@olenagerasimova , fixed in latest commit

2021-05-24 07:23 UTC, g4s8 commented
> @milkysoft please check our contributing style guide: https://github.com/artipie/artipie/blob/master/CONTRIBUTING.md
> 
> Pay attention to PR and commit message format

@milkysoft please check my comment

2021-05-25 06:32 UTC, g4s8 commented
@milkysoft please notify the reviewer when you resolve PR issues

2021-05-25 06:52 UTC, g4s8 requested changes
@milkysoft please see my comments. Don't forget to ping reviewers after fixes

2021-05-25 06:52 UTC, g4s8 commented on src/main/java/com/artipie/gem/GemInfo.java
> +    private final Ruby ruby;
It's better to lazy-initialize Ruby runtime on first request to avoid IO operations in the constructor.

2021-05-25 06:52 UTC, g4s8 commented on src/main/java/com/artipie/gem/GemInfo.java
> +        this.runtime.eval(this.ruby, "require 'rubygems/commands/contents_command.rb'");
This line should be moved to initialization, no need to call it on each request

2021-05-25 06:52 UTC, g4s8 commented on src/main/java/com/artipie/gem/GemInfo.java
> +                }
I think it'd be better to move this logic to a new class which can convert Ruby object to JSON with a separate test (right now these lines are not covered at all -- see Codecov comments and report)

2021-05-25 06:52 UTC, g4s8 commented on src/main/java/com/artipie/gem/GemInfo.java
> +                String.format("Gem::Commands::ContentsCommand.new.spec_for('%s')", gem)
This line performs some inspections on the local get file, but it's not located here (current working directory is empty, all files are located in storage). We need to sync gem fie first before spec analysis.

2021-05-25 06:52 UTC, g4s8 commented on src/test/java/com/artipie/gem/QueryGemITCase.java
> +                new RequestLine(RqMethod.GET, "/api/v1/gems/did_you_mean.json"),
Where this gem is located?

2021-05-25 06:52 UTC, g4s8 commented on src/test/java/com/artipie/gem/QueryGemITCase.java
> +            Files.readAllBytes(Paths.get("./src/test/resources/test_response.json"))
Accessing test resources using relative path is not correct

2021-05-25 06:52 UTC, g4s8 commented on src/test/java/com/artipie/gem/QueryGemITCase.java
> +                    new RsHasBody(content, StandardCharsets.UTF_8)
Comparing the body of JSON response could lead to false test errors in case if formatting of JSON changes or fields order changes. I'd suggest using JSON matchers to verify the response (you can find some examples in npm-adapter, e.g. in this test: https://github.com/artipie/npm-adapter/blob/c2da54c976fad1c19dccad9214497dd0a0e46df4/src/test/java/com/artipie/npm/http/DeprecateSliceTest.java#L101-L116)

2021-05-25 08:38 UTC, g4s8 commented
> # [Codecov](https://codecov.io/gh/artipie/gem-adapter/pull/94?src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=artipie) Report
> 
> > Merging [#94](https://codecov.io/gh/artipie/gem-adapter/pull/94?src=pr&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=artipie) ([d96d7a5](https://github.com/artipie/gem-adapter/commit/d96d7a53cc8c0666be30f2510d2af54fcb775808)) into [master](https://codecov.io/gh/artipie/gem-adapter/commit/5869abb32e6dff0980b364391cef5d036da7b0e9?el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=artipie) ([5869abb](https://github.com/artipie/gem-adapter/commit/5869abb32e6dff0980b364391cef5d036da7b0e9)) will **decrease** coverage by `1.38%`.
> > The diff coverage is `18.75%`.
> 
> [![Impacted file tree graph](https://camo.githubusercontent.com/6627640efc352cf4046e2097203215e56ed97713551e6c98e935e537b89353e2/68747470733a2f2f636f6465636f762e696f2f67682f617274697069652f67656d2d616461707465722f70756c6c2f39342f6772617068732f747265652e7376673f77696474683d363530266865696768743d313530267372633d707226746f6b656e3d416a686f685a4a7143662675746d5f6d656469756d3d726566657272616c2675746d5f736f757263653d6769746875622675746d5f636f6e74656e743d636f6d6d656e742675746d5f63616d706169676e3d70722b636f6d6d656e74732675746d5f7465726d3d61727469706965)](https://codecov.io/gh/artipie/gem-adapter/pull/94?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=artipie)
> 
> ```diff
> @@             Coverage Diff              @@
> ##             master      #94      +/-   ##
> ============================================
> - Coverage     46.45%   45.06%   -1.39%     
>   Complexity       24       24              
> ============================================
>   Files             8        8              
>   Lines           155      162       +7     
>   Branches          6        7       +1     
> ============================================
> + Hits             72       73       +1     
> - Misses           83       89       +6     
> ```
> 
> [Impacted Files](https://codecov.io/gh/artipie/gem-adapter/pull/94?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=artipie) 	Coverage Δ 	Complexity Δ 	
> [src/main/java/com/artipie/gem/GemSlice.java](https://codecov.io/gh/artipie/gem-adapter/pull/94/diff?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=artipie#diff-c3JjL21haW4vamF2YS9jb20vYXJ0aXBpZS9nZW0vR2VtU2xpY2UuamF2YQ==) 	`86.66% <ø> (ø)` 	`4.00 <0.00> (ø)` 	
> [src/main/java/com/artipie/gem/GemInfo.java](https://codecov.io/gh/artipie/gem-adapter/pull/94/diff?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=artipie#diff-c3JjL21haW4vamF2YS9jb20vYXJ0aXBpZS9nZW0vR2VtSW5mby5qYXZh) 	`20.83% <18.75%> (-2.70%)` 	`2.00 <1.00> (ø)` 	
> 
> [Continue to review full report at Codecov](https://codecov.io/gh/artipie/gem-adapter/pull/94?src=pr&el=continue&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=artipie).
> 
> > **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=artipie)
> > `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> > Powered by [Codecov](https://codecov.io/gh/artipie/gem-adapter/pull/94?src=pr&el=footer&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=artipie). Last update [5869abb...d96d7a5](https://codecov.io/gh/artipie/gem-adapter/pull/94?src=pr&el=lastupdated&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=artipie). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=artipie).

@milkysoft also, please check Codecov report - this PR introduces a big coverage degrade, since the majority of the code is not tested at all.

2021-05-25 11:50 UTC, milkysoft commented on src/test/java/com/artipie/gem/QueryGemITCase.java
> +                new RequestLine(RqMethod.GET, "/api/v1/gems/did_you_mean.json"),
@g4s8 , **did_you_mean** gem is part of standard ruby library, included during ruby (JRuby) installation.

2021-05-25 11:52 UTC, milkysoft commented on src/test/java/com/artipie/gem/QueryGemITCase.java
> +            Files.readAllBytes(Paths.get("./src/test/resources/test_response.json"))
@g4s8 , thanks, fixed in latest [commit](https://github.com/artipie/gem-adapter/pull/94/commits/9d9a3af6bacdad3c84e70fcfcf14a49193f17b37)

2021-05-25 12:04 UTC, milkysoft commented on src/test/java/com/artipie/gem/QueryGemITCase.java
> +                    new RsHasBody(content, StandardCharsets.UTF_8)
@g4s8 , thanks, fixed in latest [commit](https://github.com/artipie/gem-adapter/pull/94/commits/9d9a3af6bacdad3c84e70fcfcf14a49193f17b37)

2021-05-25 12:05 UTC, milkysoft commented on src/main/java/com/artipie/gem/GemInfo.java
> +        this.runtime.eval(this.ruby, "require 'rubygems/commands/contents_command.rb'");
@g4s8 , thanks, fixed in latest [commit](https://github.com/artipie/gem-adapter/pull/94/commits/5a79e7dd06161f843be162b70a81b8a99901844b)

2021-05-25 12:06 UTC, milkysoft commented on src/main/java/com/artipie/gem/GemInfo.java
> +    private final Ruby ruby;
@g4s8 , thanks, fixed in latest [commit](https://github.com/artipie/gem-adapter/pull/94/commits/5a79e7dd06161f843be162b70a81b8a99901844b)

2021-05-26 11:07 UTC, milkysoft commented on src/main/java/com/artipie/gem/GemInfo.java
> +                String.format("Gem::Commands::ContentsCommand.new.spec_for('%s')", gem)
@g4s8 , thanks, fixed in latest [commit](https://github.com/artipie/gem-adapter/pull/94/commits/8670baeaab4152b48eb1187c872ebf16b6b444b3)

2021-05-27 09:30 UTC, g4s8 requested changes
@milkysoft please check a few comments

2021-05-27 09:30 UTC, g4s8 commented on src/main/java/com/artipie/gem/GemInfo.java
> +    public GemInfo(final Storage storage, final RubyRuntimeAdapter runtime, final Ruby ruby) {
I don't think we need to expose internals to the public API level - it's an HTTP endpoint, so user doesn't know how it works internally, and we may change the implementation later. By requiring a `RubyRuntime` and `Ruby` we are making a **high coupling** between component (gem-adapter) users components like customers service or artipie/artipie. Let's hide the implementation behind the interface like we did with `SubmitGem` - we can move the logic with JRuby to `Gem` implementation and use interface to build a JSON object by gem name.

2021-05-27 09:30 UTC, g4s8 commented on src/main/java/com/artipie/gem/GemInfo.java
> +    public void initialize() {
It's not a good practice to require additional initialization besides the constructor call, let's make it implicit and call the script when creating a new `Ruby` and runtime instances

2021-05-27 09:30 UTC, g4s8 commented on src/main/java/com/artipie/gem/GemInfo.java
> +    public static GemInfo createNew(final Storage storage) {
No need to create factory methods for `Slice` implementation, constructor is enough

2021-05-27 09:30 UTC, g4s8 commented on src/main/java/com/artipie/gem/GemInfo.java
> +            final String script = String.format(
These lines are still not covered by tests (see Codecov report), it means the test case doesn't match the `PATH_PATTERN` regex

2021-05-27 09:30 UTC, g4s8 commented on src/main/java/com/artipie/gem/GemInfo.java
> +        for (int ind = 0; ind < vars.size(); ind = ind + 1) {
`vars` is a list, you can iterate over items using for-each loop or `vars.stream()` API

2021-05-27 09:30 UTC, g4s8 commented on src/main/java/com/artipie/gem/GemInfo.java
> +            if (var.getName().substring(0, 1).equals("@")) {
This condition could be checked by `String.startsWith` or `String.charAt`

2021-05-27 09:30 UTC, g4s8 commented on src/main/java/com/artipie/gem/GemInfo.java
> +                        .thenApply(none -> true)
This method also is not covered by tests

2021-05-27 09:30 UTC, g4s8 commented on src/main/java/com/artipie/gem/GemInfo.java
> +                if (file.contains(gem) && file.contains(".gem")) {
This condition could be performed using filter stream API started on previous lines: `Files.walk().map().filter().forEach()`

2021-05-27 09:30 UTC, g4s8 commented on src/main/java/com/artipie/gem/GemInfo.java
> +            Logger.error(GemInfo.class, exc.getMessage());
It's a bad practice to shallow exceptions, user will not know that error occurs, let's propagate it to the top level

2021-05-27 09:30 UTC, g4s8 commented on src/main/java/com/artipie/gem/GemInfo.java
> +        ).join();
Please avoid using `join()` or `get()` of `CompletableFuture` in production code, it could be used **only in tests**. This call blocks the whole thread until the copy operation completes

2021-05-27 09:30 UTC, g4s8 commented on src/test/java/com/artipie/gem/QueryGemITCase.java
> +public class QueryGemITCase {
If we don't use external component (don't start Vertx server) it could be converted from integration test to unit test - just change the name from `QueryGemITCase` to `GemInfoTest` and surefire plugin will run it as a unit-test

2021-05-27 10:11 UTC, milkysoft commented on src/main/java/com/artipie/gem/GemInfo.java
> +        for (int ind = 0; ind < vars.size(); ind = ind + 1) {
@g4s8 , thanks, it is great idea. But in this cycle index, `ind` is used for two purposes:
1. To obtain variable name, which could be converted to for-each loop
2. To obtain gem object variable value, which could be done only by using index, not the name, thus this part can not be converted to for-each/stream

2021-05-27 13:00 UTC, milkysoft commented on src/main/java/com/artipie/gem/GemInfo.java
> +            Logger.error(GemInfo.class, exc.getMessage());
@g4s8 , fixed in latest commit

2021-05-27 13:00 UTC, milkysoft commented on src/test/java/com/artipie/gem/QueryGemITCase.java
> +public class QueryGemITCase {
@g4s8 , fixed in latest commit

2021-05-27 13:00 UTC, milkysoft commented on src/main/java/com/artipie/gem/GemInfo.java
> +        for (int ind = 0; ind < vars.size(); ind = ind + 1) {
@g4s8 , fixed in latest commit

2021-05-27 13:00 UTC, milkysoft commented on src/main/java/com/artipie/gem/GemInfo.java
> +    public static GemInfo createNew(final Storage storage) {
@g4s8 , fixed in latest commit

2021-05-27 13:01 UTC, milkysoft commented on src/main/java/com/artipie/gem/GemInfo.java
> +    public void initialize() {
@g4s8 , fixed in latest commit

2021-05-27 13:01 UTC, milkysoft commented on src/main/java/com/artipie/gem/GemInfo.java
> +    public GemInfo(final Storage storage, final RubyRuntimeAdapter runtime, final Ruby ruby) {
@g4s8 , fixed in latest commit

2021-05-28 12:29 UTC, milkysoft commented
@olenagerasimova , Pull request is ready to merge and waiting for your approval. I confirm the code is correct and clean.

2021-05-28 13:11 UTC, olenagerasimova approved these changes
@milkysoft thanks

2021-05-31 07:51 UTC, g4s8 requested changes
@milkysoft please check unresolved reiew comments

2021-05-31 07:51 UTC, g4s8 commented on src/main/java/com/artipie/gem/GemInfo.java
> +                }
@milkysoft please pay attention to this comment, it's not addressed yet

2021-05-31 09:42 UTC, zorcheal commented on src/main/java/com/artipie/gem/GemInfo.java
> +            final String script = String.format(
@g4s8 , fixed in latest commit

2021-05-31 13:26 UTC, milkysoft commented
@g4s8 , `RubyObjJson` class implemented, which takes directory Path and gem name to extract JSON information and returns `JsonObjectBuilder`, corresponding `RubyObjJsonTest` covers new SDK functionality

2021-06-01 08:55 UTC, g4s8 requested changes
@milkysoft please check a few comments

2021-06-01 08:55 UTC, g4s8 commented on src/main/java/com/artipie/gem/RubyObjJson.java
> +        );
This line could be evaluated only once during initialization

2021-06-01 08:55 UTC, g4s8 commented on src/main/java/com/artipie/gem/RubyObjJson.java
> +                final String script = "Gem::Package.new('"
I'd suggest using `String.format` here instead of concatenation, since it's not easy to read now

2021-06-01 08:55 UTC, g4s8 commented on src/main/java/com/artipie/gem/RubyObjJson.java
> +        RubyObject gemobject = null;
This variable could be `final` , and it's no need to assign `null` here

2021-06-01 08:55 UTC, g4s8 commented on src/main/java/com/artipie/gem/RubyObjJson.java
> +            throw new UncheckedIOException(exc);
Please use `ArtipieIOException` from `com.artipie:asto:1.1.0`

2021-06-01 08:55 UTC, g4s8 commented on src/test/resources/test_response.json
> +{"doc_dir":"","homepage":"https://github.com/yuki24/did_you_mean","autorequire":"","specification_version":"4","required_ruby_version":">= 2.5.0dev","required_rubygems_version":">= 0","extensions":"[
It seems we don't need this file anymore

2021-06-04 09:30 UTC, g4s8 requested changes
@milkysoft please check my comments

2021-06-04 09:30 UTC, g4s8 commented on src/main/java/com/artipie/gem/GemInfo.java
> +     * Ruby interpreter.
Why storage is a "Ruby interpreter"?

2021-06-04 09:30 UTC, g4s8 commented on src/main/java/com/artipie/gem/GemInfo.java
> +                        RsJson res = null;
Please don't return `null`s to response, it'll fail the `Slice` server with `NullPointerException`

2021-06-04 09:30 UTC, g4s8 commented on src/main/java/com/artipie/gem/GemInfo.java
> +        String gemfile = "";
Empty strings is not a valid Gem file

2021-06-04 09:30 UTC, g4s8 commented on src/main/java/com/artipie/gem/GemInfo.java
> +                                new RubyObjJson().createJson(
What is the state of this object?

2021-06-08 11:28 UTC, g4s8 requested changes
@milkysoft please check my comments. Also, the file `src/test/resources/thor-1.1.0.gem` is not used and could be removed.

2021-06-08 11:28 UTC, g4s8 commented on src/main/java/com/artipie/gem/GemInfo.java
> +    public GemInfo(final Path dir) {
`Slice` should not depend on storage implementation, let's use just `Storage` interface which will be configured outside

2021-06-08 11:28 UTC, g4s8 commented on src/main/java/com/artipie/gem/GemInfo.java
> +                            FileUtils.deleteDirectory(new File(tmpdir.toString()));
You can use `Files.delete(tmpdir)` here instead of this statement.

2021-06-08 11:28 UTC, g4s8 commented on src/main/java/com/artipie/gem/GemInfo.java
> +     * Copy storage from src to dst.
This javadoc is not correct

2021-06-08 11:28 UTC, g4s8 commented on src/main/java/com/artipie/gem/RubyObjJson.java
> +class RubyObjJson {
This class could be final

2021-06-08 11:28 UTC, g4s8 commented on src/main/java/com/artipie/gem/RubyObjJson.java
> +     * Install new gem.
The javadoc is not correct here

2021-06-08 11:28 UTC, g4s8 commented on src/main/java/com/artipie/gem/RubyObjJson.java
> +        final String script = String.format("Gem::Package.new('%s').spec", gempath.toString());
This variable could be inlined into the next statement

2021-06-08 11:28 UTC, g4s8 commented on src/main/java/com/artipie/gem/RubyObjJson.java
> +        );
This comment was not fixed

2021-06-08 12:39 UTC, milkysoft commented
@g4s8 , unfortunately `FileUtils.deleteDirectory(new File(tmpdir.toString()));` cannot be replaced with more elegant `Files.delete(tmpdir)` as the last statement fail to delete non empty directories:
```
java.util.concurrent.CompletionException: com.artipie.asto.ArtipieIOException: java.nio.file.DirectoryNotEmptyException: /tmp/gem2823327296920837474
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
```

All other comments are fixed in latest commit

2021-06-08 13:41 UTC, g4s8 approved these changes
@milkysoft thanks

2021-06-09 08:27 UTC, merged