Issue #85 Create GemInfo interface
artipie/gem-adapter pull request #96
Opened 2021-06-11 09:45 UTC by milkysoft

1. Add GemInfo interface
2. Create GemInfoClass to extract gem information json similar to SubmitGem
3. Make Gem class use both, GemIndex and GemInfo
4. Rewrite unit tests for GemInfo to use Gem SDK

2021-06-16 13:25 UTC, g4s8 requested changes
@milkysoft please check my comment. Also, the commit history looks not accurate, please rebase.

2021-06-16 13:25 UTC, g4s8 commented on src/main/java/com/artipie/gem/Gem.java
> +    private final AtomicReference<GemInfo> infocache;
These two atomic-references looks very similar, both interfaces (`GemInfo` and `GemIndex`) could be instantiated simultaneously, since both uses atomic references only for lazy loading of ruby runtime and ruby interpreter

2021-06-16 13:25 UTC, g4s8 commented on src/main/java/com/artipie/gem/Gem.java
> +        this(storage, () -> RubyGemIndex.createNew(), () -> RubyObjJson.createNew());
Now `RubyGemIndex` and `RubyObjJson` can use same runtime and interpreter instances

2021-06-16 13:25 UTC, g4s8 commented on src/main/java/com/artipie/gem/Gem.java
> +                    key -> vars.contains(key.string()) || key.string().contains(gem.string())
I didn't get this filter expression: why we check if key is in the set of items and then check if gem key converted to string is a substring of key string representation? This code seems to be not obvious.

2021-06-16 13:25 UTC, g4s8 commented on src/main/java/com/artipie/gem/Gem.java
> +    private CompletionStage<Key> getGemFile(final Key gem) {
`Key` is not a file, we can't say that this method return a full path then

2021-06-16 13:25 UTC, g4s8 commented on src/main/java/com/artipie/gem/Gem.java
> +                        return key.string().contains(gem.string());
What this filter supposed to do? E.g. if we have gem called `foo` and we have another gem called `foo-bar`, then you want to find both? I didn't get this

2021-06-16 13:25 UTC, g4s8 commented on src/main/java/com/artipie/gem/GemInfoClass.java
> +public final class GemInfoClass implements Slice {
I don't this that class is good name for class. And what happens with `GemInfoSlice`?

2021-06-16 13:25 UTC, g4s8 commented on src/main/java/com/artipie/gem/RubyGemIndex.java
> +                "require 'rubygems/indexer.rb'\n"
We can call `require` only once during initialization, like it was implemented already

2021-06-18 09:39 UTC, milkysoft commented on src/main/java/com/artipie/gem/Gem.java
> +                        return key.string().contains(gem.string());
@g4s8 , the concept here is the following. Gem is operating with Keys and Storages. While Ruby itself and in our case - RubyObjJson operates with files. There should be some interface to translate between both. The `gem` in the code above is the name without version. Thus generally speaking you are right, if there are two gems containing the same string, randomly selected the first one will be used to extract info back to the user

2021-06-18 09:40 UTC, milkysoft commented on src/main/java/com/artipie/gem/Gem.java
> +    private CompletionStage<Key> getGemFile(final Key gem) {
@g4s8 , the concept here is the following. Gem is operating with Keys and Storages. While Ruby itself and in our case - RubyObjJson operates with files. There should be some interface to translate between both.

2021-06-18 09:44 UTC, milkysoft commented on src/main/java/com/artipie/gem/Gem.java
> +                    key -> vars.contains(key.string()) || key.string().contains(gem.string())
@g4s8 the concept here is the following. Usually, the 'gem` in the code above is the gem name, without version and extension. While the file name, which represents by `key` is usually the full gem name, including name, version and extension. While it works in case `info` route, in `dependencies` route case it is required to find the file by pure gem name, which was implemented

2021-06-23 13:06 UTC, milkysoft commented on src/main/java/com/artipie/gem/Gem.java
> +        this(storage, () -> RubyGemIndex.createNew(), () -> RubyObjJson.createNew());
@g4s8 , Single ruby and runtime for booth GemIndexer and GemInfo implemented with latest commit

2021-06-23 13:22 UTC, milkysoft commented on src/main/java/com/artipie/gem/RubyGemIndex.java
> +                "require 'rubygems/indexer.rb'\n"
@g4s8 , Require is fixed with latest commit to be called only once for GemIndexer and Geminfo

2021-06-24 13:09 UTC, milkysoft commented on src/main/java/com/artipie/gem/GemInfoClass.java
> +public final class GemInfoClass implements Slice {
@g4s8 , `GemInfoClass` renmaed to `GetGemInfo` similar to `SubmitGem` class with latest commit

2021-06-24 13:15 UTC, milkysoft commented on src/main/java/com/artipie/gem/Gem.java
> +    private final AtomicReference<GemInfo> infocache;
@g4s8 , AtomicReference accepts as parameter only one class, thus for each required classes `GemInfo` and `GemIndex` we use separate AtomicReferences.

2021-06-25 14:25 UTC, g4s8 requested changes
@milkysoft please see my comments

2021-06-25 14:25 UTC, g4s8 commented on src/main/java/com/artipie/gem/Gem.java
> +        this.ruby = JavaEmbedUtils.initialize(Collections.emptyList());
Please don't perform any heavy operations in constructor

2021-06-25 14:25 UTC, g4s8 commented on src/main/java/com/artipie/gem/Gem.java
> + * @checkstyle ClassDataAbstractionCouplingCheck (500 lines)
This suppression is not a good indicator, it means that the class should be decomposed

2021-06-25 14:25 UTC, g4s8 commented on src/main/java/com/artipie/gem/Gem.java
> +        this.indexer = () -> new RubyGemIndex(this.runtime, this.ruby);
Creating a new instance is a very fast operation, no need to wrap it with lambdas and atomics. Previously, atomic was used for ruby runtime and interpreter initialization for SDK

2021-06-25 14:25 UTC, g4s8 commented on src/main/java/com/artipie/gem/Gem.java
> +    public CompletionStage<JsonObject> getInfo(final Key gem) {
No need to use `get` prefix here, `info()` is good enough like a property description.

2021-06-25 14:25 UTC, g4s8 commented on src/main/java/com/artipie/gem/Gem.java
> +                            removeTempDir(tmpdir, null);
The exception could be thrown before this line, and temp dir won't be removed in this case. It's a file leakage.

2021-06-25 14:25 UTC, g4s8 commented on src/main/java/com/artipie/gem/Gem.java
> +                        } catch (final InterruptedException | ExecutionException exc) {
`InterruptedException` should not cause IO errors, please read how to handle Java interruptions correctly

2021-06-25 14:25 UTC, g4s8 commented on src/main/java/com/artipie/gem/Gem.java
> +                    key -> vars.contains(key.string()) || key.string().contains(gem.string())
The issue is not solved here: the key may contain the gem name and not being the expected gem key at the same time, so if some key has `abc` in path (e.g. `abc/another-gem`, and gem's name is `abc`, then we may get another gem by mistake. We need to check the name explicitly.

2021-06-25 14:25 UTC, g4s8 commented on src/main/java/com/artipie/gem/Gem.java
> +    private CompletionStage<Key> getGemFile(final Key gem) {
When we copy storage objects to file system, then we can operate with `Path`s to avoid mixed abstractions

2021-06-25 14:25 UTC, g4s8 commented on src/main/java/com/artipie/gem/Gem.java
> +                        return key.string().contains(gem.string());
And same here: we need to check it explicitly

2021-06-25 14:25 UTC, g4s8 commented on src/main/java/com/artipie/gem/GemInfo.java
> +            synchronized (this.origin) {
If we use share ruby runtime, then we need to synchronize on shared object (the same for `GemInfo` and `GemIndex`). Ideally, we may check if the synchronization is actually needed, since JRuby runtime may have internal and fast synchronization.

2021-06-30 11:06 UTC, milkysoft commented on src/main/java/com/artipie/gem/Gem.java
> +                            removeTempDir(tmpdir, null);
@g4s8 , I would suggest to use `try .. catch... finally` and call `removeTempDir` in `finally { ... }` block

2021-06-30 11:29 UTC, milkysoft commented on src/main/java/com/artipie/gem/Gem.java
> +    public CompletionStage<JsonObject> getInfo(final Key gem) {
@g4s8 , fixed in latest commit

2021-07-05 08:12 UTC, milkysoft commented on src/main/java/com/artipie/gem/Gem.java
> + * @checkstyle ClassDataAbstractionCouplingCheck (500 lines)
@g4s8 , agreed, please provide which methods to be moved to another class

2021-07-05 08:13 UTC, milkysoft commented on src/main/java/com/artipie/gem/Gem.java
> +        this.indexer = () -> new RubyGemIndex(this.runtime, this.ruby);
@g4s8 , currently lambdas are used for Supplier, otherwise cache types should be changed. Below, we are considering to remove cache completely

2021-07-05 08:15 UTC, milkysoft commented on src/main/java/com/artipie/gem/Gem.java
> +                        } catch (final InterruptedException | ExecutionException exc) {
@g4s8 , here I propose to use `finally` statement to remove temporarily directory in any case

2021-07-05 08:17 UTC, milkysoft commented on src/main/java/com/artipie/gem/GemInfo.java
> +            synchronized (this.origin) {
@g4s8 , filtering has been adjusted. For cache, any solution is OK for me.

2021-07-05 08:28 UTC, milkysoft commented on src/main/java/com/artipie/gem/Gem.java
> +    private CompletionStage<Key> getGemFile(final Key gem) {
@g4s8 , `getGemFile` functionality is to return the gem file name with version and extension from temporarily directory root folder. It is supposed that all required files are uploaded into Storage root and then they will be copied to temporarily folder root.

2021-07-05 08:30 UTC, milkysoft commented on src/main/java/com/artipie/gem/Gem.java
> +                        return key.string().contains(gem.string());
@g4s8 , the filtering has been ajusted. Also, to be considered is the following case: when `/api/v1/deendencies` route is called say for **gviz** name, then rubygems returns info for all gems with names including gviz, which is also mentioned in documentation for this route.

2021-07-05 09:24 UTC, g4s8 requested changes
@milkysoft please check my answers

2021-07-05 09:24 UTC, g4s8 commented on src/main/java/com/artipie/gem/Gem.java
> +            .flatMapObservable(Observable::fromIterable).forEach(future::complete);
`future::complete` - please use `SingleInterop` instead

2021-07-05 09:24 UTC, g4s8 commented on src/main/java/com/artipie/gem/GemInfo.java
> +    JsonObject getinfo(Path gempath);
No need to use `get` prefix, `info` is informative enough

2021-07-05 09:24 UTC, g4s8 commented on src/main/java/com/artipie/gem/GemInfo.java
> +            synchronized (this.origin) {
this issue was not fixed

2021-07-05 09:24 UTC, g4s8 commented on src/main/java/com/artipie/gem/GetGemInfo.java
> +    public static final Pattern PATH_PATTERN = Pattern.compile("/api/v1/gems/([\\w]+).(json|yml)");
Do we support `yml` too?

2021-07-05 09:24 UTC, g4s8 commented on src/main/java/com/artipie/gem/RubyGemIndex.java
> +    private boolean issetup;
This field is not thread safe

2021-07-05 09:24 UTC, g4s8 commented on src/main/java/com/artipie/gem/RubyObjJson.java
> +    public JsonObject getinfo(final Path gempath) {
No need to use get prefixes

2021-07-05 09:24 UTC, g4s8 commented on src/test/java/com/artipie/gem/RubyObjJsonTest.java
> +    public void createJsonByPath(@TempDir final Path tmp) throws IOException,
In unit test you can just declare `throws Exception` to avoid listing all possible types here

2021-07-05 09:24 UTC, g4s8 commented on src/main/java/com/artipie/gem/Gem.java
> + * @checkstyle ClassDataAbstractionCouplingCheck (500 lines)
Please try to think yourself how to reduce the coupling between classes

2021-07-05 10:55 UTC, milkysoft commented on src/main/java/com/artipie/gem/GetGemInfo.java
> +    public static final Pattern PATH_PATTERN = Pattern.compile("/api/v1/gems/([\\w]+).(json|yml)");
@g4s8 , as I see calling to routes like `https://rubygems.org/api/v1/gems/gviz.yml` produces no results, only `https://rubygems.org/api/v1/gems/gviz.json` at the end returns data back. Thus for now no urgency to implement yml output, although it is OK to create new Issue for this format

2021-07-05 12:06 UTC, g4s8 commented on src/main/java/com/artipie/gem/GetGemInfo.java
> +    public static final Pattern PATH_PATTERN = Pattern.compile("/api/v1/gems/([\\w]+).(json|yml)");
@milkysoft yes, this is right direction. In that case, we need to return standard [Not Implemented](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/501) response for `yml` requests, and fix it later.

2021-07-06 14:10 UTC, milkysoft commented on src/main/java/com/artipie/gem/RubyObjJson.java
> +    public JsonObject getinfo(final Path gempath) {
@g4s8 , Fixed in latest commit

2021-07-06 14:10 UTC, milkysoft commented on src/main/java/com/artipie/gem/RubyGemIndex.java
> +    private boolean issetup;
@g4s8 , Reading and Setting this field fixed in latest commit

2021-07-06 14:11 UTC, milkysoft commented on src/main/java/com/artipie/gem/GetGemInfo.java
> +    public static final Pattern PATH_PATTERN = Pattern.compile("/api/v1/gems/([\\w]+).(json|yml)");
@g4s8 , Fixed in latest commit, corresponding unit test added

2021-07-06 14:13 UTC, milkysoft commented on src/test/java/com/artipie/gem/RubyObjJsonTest.java
> +    public void createJsonByPath(@TempDir final Path tmp) throws IOException,
@g4s8 , fixed in latest commit

2021-07-06 14:52 UTC, milkysoft commented on src/main/java/com/artipie/gem/Gem.java
> +            .flatMapObservable(Observable::fromIterable).forEach(future::complete);
@g4s8 , fixed in latest commit

2021-07-06 14:53 UTC, milkysoft commented on src/main/java/com/artipie/gem/Gem.java
> +    public void initialize() {
@g4s8 , we either initialise in constructor or in separate function. If initialisation is too heavy for constructor, then we consider separate function

2021-07-07 11:48 UTC, g4s8 commented on src/main/java/com/artipie/gem/GetGemInfo.java
> +    public static final Pattern PATH_PATTERN = Pattern.compile("/api/v1/gems/([\\w]+).(json|yml)");
@milkysoft I don't see these changes

2021-07-07 11:48 UTC, g4s8 commented on src/main/java/com/artipie/gem/Gem.java
> +    public void initialize() {
Why can't we just lazy initialize ruby interpreter and runtime?

2021-07-08 10:38 UTC, g4s8 requested changes
@milkysoft please see new comments and please check a few old not resolved comments too: https://github.com/artipie/gem-adapter/pull/96/files#conversations-menu

2021-07-12 09:20 UTC, milkysoft commented on src/main/java/com/artipie/gem/Gem.java
> +                                .get();
@g4s8 , thenCompose is not applicable here, as inside transfer needed access to many variables, including: `tmpdir`, produced on previous step,  `rubyJson` from `sharedInfo`. If we use thenCompose it produces CompletionStage<CompletionStage> ..., which is incorrect.

2021-07-12 09:26 UTC, milkysoft commented on src/main/java/com/artipie/gem/Gem.java
> +    private CompletionStage<List<Key>> getGemFile(final Key gem) {
@g4s8 , `gem` here may have the following values: `gviz`, `thor`, etc... Documentation is correct, what has been changed is that instead of getting one value for path, which stucks when gem is absent, the method returns so called "List", actually only one element will be used from this List.
So, filter(...).get(1) has been replaced with List... get(1)

2021-07-12 09:33 UTC, milkysoft commented on src/main/java/com/artipie/gem/Gem.java
> +    public void initialize() {
@g4s8 , Fixed in latest commit

2021-07-12 09:39 UTC, milkysoft commented on src/main/java/com/artipie/gem/Gem.java
> +                        } catch (final InterruptedException | ExecutionException exc) {
@g4s8 , InterruptedException is produced when User manually interrupts program execution, including typing Ctrl+C or equivalent. These are special cases and if program interrupted manually, all resources could be released manually as well. The code in place does the best job possible to clean up system from temporarily created files and folders.

2021-07-16 06:33 UTC, closed without merging